-- Seed additional CMS keys for simplified Content Manager
INSERT INTO public.site_content (section, content_key, content_value) VALUES
  ('homepage', 'platform_intro_badge', '"Build the Agentic Enterprise"'::jsonb),
  ('homepage', 'platform_intro_title', '"Everything you need to become an"'::jsonb),
  ('homepage', 'platform_intro_desc', '"Unify sales, service, marketing, and data on one AI-powered platform built for modern enterprises."'::jsonb),
  ('homepage', 'product_section_title', '"The Complete Product Suite"'::jsonb),
  ('homepage', 'product_section_desc', '"Six powerful clouds. One unified platform."'::jsonb),
  ('homepage', 'features_section_title', '"Why teams choose HYSYS"'::jsonb),
  ('homepage', 'features_section_desc', '"Enterprise-grade capabilities out of the box."'::jsonb),
  ('products', 'productsTitle', '"Cloud Products"'::jsonb),
  ('products', 'productsDesc', '"Everything you need to connect with customers, automate processes, and grow your business."'::jsonb),
  ('industries', 'industriesTitle', '"Industry Solutions"'::jsonb),
  ('industries', 'industriesDesc', '"Purpose-built solutions for every industry, designed with your unique challenges in mind."'::jsonb),
  ('contact', 'contactTitle', '"Contact Us"'::jsonb),
  ('contact', 'contactDesc', '"We would love to hear from you. Reach out for sales, support, or partnership inquiries."'::jsonb),
  ('contact', 'getInTouch', '"Get in Touch"'::jsonb),
  ('contact', 'sendUsMessage', '"Send Us a Message"'::jsonb),
  ('contact', 'phone_numbers', '"+256 782 602854\nMon–Fri 8am–6pm EAT"'::jsonb),
  ('contact', 'email_address', '"info@hysysglobal.com"'::jsonb),
  ('contact', 'office_address', '"Kampala, Uganda\nPlot 42, Business District"'::jsonb),
  ('contact', 'business_hours', '"Mon–Fri: 8:00 AM – 6:00 PM EAT\nSat: 9:00 AM – 1:00 PM EAT"'::jsonb),
  ('stories', 'customerStoriesTitle', '"Customer Success Stories"'::jsonb),
  ('stories', 'customerStoriesDesc', '"See how organizations worldwide transform with HYSYS."'::jsonb),
  ('stories', 'shareYourStory', '"Ready to write your success story?"'::jsonb),
  ('stories', 'shareYourStoryDesc', '"Join thousands of companies achieving remarkable results with HYSYS."'::jsonb),
  ('stories', 'contactUsBtn', '"Contact Us"'::jsonb),
  ('events', 'eventsTitle', '"Events & Experiences"'::jsonb),
  ('events', 'eventsDesc', '"Participate in live summits, workshops, and partner forums."'::jsonb),
  ('events', 'events_section_title', '"Learn, network, and lead change"'::jsonb),
  ('events', 'events_section_desc', '"Experience HYSYS events tailored for customers, partners, and IT teams."'::jsonb),
  ('events', 'events_list', '[
    {"id":"summit","date":"June 12, 2026","title":"HYSYS Global Summit","description":"Join customers, partners, and product leaders for innovation sessions, hands-on workshops, and networking.","highlight":"Live keynotes + panel discussions"},
    {"id":"forum","date":"September 4, 2026","title":"Customer Success Forum","description":"Explore customer stories, best practices, and success strategies for CRM and AI-powered operations.","highlight":"Case study deep dives"},
    {"id":"workshop","date":"November 18, 2026","title":"Cloud Transformation Workshop","description":"Practical sessions for IT teams planning secure cloud migrations and scalable platform rollouts.","highlight":"Architecture and security workshops"}
  ]'::jsonb),
  ('global', 'footer_tagline', '"Empowering businesses with intelligent CRM solutions."'::jsonb),
  ('global', 'support_email', '"support@hysysglobal.com"'::jsonb),
  ('global', 'support_phone', '"+256 782 602854"'::jsonb),
  ('global', 'faq_section_title', '"Frequently Asked Questions"'::jsonb)
ON CONFLICT (section, content_key) DO NOTHING;
