-- Phase 3 CMS wiring: demo request, footer, contact/events form labels, detail headings

INSERT INTO public.site_content (section, content_key, content_value) VALUES
  ('demo_request', 'demo_hero_badge', '"Demo"'),
  ('demo_request', 'demo_title', '"Request a personalised demo"'),
  ('demo_request', 'demo_desc', '"See how Marmidon ERP fits your organisation. Our team will tailor a demo to your modules and industry."'),
  ('demo_request', 'form_first_name_label', '"First name *"'),
  ('demo_request', 'form_last_name_label', '"Last name *"'),
  ('demo_request', 'form_email_label', '"Work email *"'),
  ('demo_request', 'form_company_label', '"Company name *"'),
  ('demo_request', 'form_phone_label', '"Phone number"'),
  ('demo_request', 'form_modules_label', '"Modules of interest *"'),
  ('demo_request', 'form_industry_label', '"Industry"'),
  ('demo_request', 'form_message_label', '"Tell us about your needs"'),
  ('demo_request', 'form_submit_label', '"Request a Demo"'),
  ('demo_request', 'form_submitting_label', '"Submitting…"'),
  ('demo_request', 'success_title', '"Demo request received"'),
  ('demo_request', 'success_desc', '"A member of our team will contact you within 24 hours to schedule your personalised demo."'),
  ('demo_request', 'success_back_label', '"Back to home"'),
  ('global', 'footer_brand_name', '"Marmidon Global Solutions Limited"'),
  ('global', 'footer_website_url', '"https://www.marmidon.com"'),
  ('global', 'footer_copyright', '"© 2026 Marmidon Global Solutions Limited. All rights reserved."'),
  ('global', 'footer_col_products', '"Products"'),
  ('global', 'footer_col_solutions', '"Solutions"'),
  ('global', 'footer_col_resources', '"Resources"'),
  ('global', 'footer_col_company', '"Company"'),
  ('global', 'footer_all_products_label', '"All products →"'),
  ('global', 'footer_all_solutions_label', '"All solutions →"'),
  ('global', 'footer_privacy_label', '"Privacy"'),
  ('global', 'footer_terms_label', '"Terms"'),
  ('global', 'footer_cookies_label', '"Cookies"'),
  ('global', 'footer_sitemap_label', '"Sitemap"'),
  ('contact', 'contact_hero_badge', '"Support & Help"'),
  ('contact', 'contact_hero_cta_primary', '"Send a Message"'),
  ('contact', 'contact_hero_cta_secondary', '"Request a Demo"'),
  ('contact', 'form_required_note', '"All fields marked * are required."'),
  ('contact', 'form_submit_label', '"Send Message"'),
  ('contact', 'form_submitting_label', '"Sending…"'),
  ('contact', 'success_title', '"Message Sent!"'),
  ('contact', 'success_desc', '"Thank you for reaching out. Our team will get back to you within 24 hours."'),
  ('contact', 'success_again_label', '"Send Another Message"'),
  ('events', 'events_hero_badge', '"Events & Experiences"'),
  ('events', 'events_hero_cta_primary', '"Request a Demo"'),
  ('events', 'events_hero_cta_secondary', '"Contact Us"'),
  ('events', 'events_section_badge', '"Upcoming Events"'),
  ('events', 'events_highlights_badge', '"Event Highlights"'),
  ('events', 'faq_section_badge', '"Event FAQs"'),
  ('products', 'detail_outcomes_badge', '"Outcomes"'),
  ('products', 'detail_outcomes_desc', '"What your organisation gains when this module is live."'),
  ('products', 'detail_integration_title', '"How it fits the Marmidon platform"'),
  ('products', 'detail_industries_title', '"Most relevant industries"'),
  ('products', 'detail_industries_desc', '"See how this module supports organisations in your sector."'),
  ('products', 'detail_faq_title', '"Frequently asked questions"'),
  ('products', 'detail_related_title', '"Works best with"'),
  ('products', 'detail_related_desc', '"Modules that connect directly with this part of Marmidon ERP."'),
  ('industries', 'detail_helps_badge', '"How Marmidon helps"'),
  ('industries', 'detail_helps_title', '"How Marmidon helps {{name}} organisations"'),
  ('industries', 'detail_helps_desc', '"Practical outcomes when finance, operations, and industry workflows run on one ERP platform."'),
  ('industries', 'detail_pain_badge', '"Challenges"'),
  ('industries', 'detail_pain_title', '"Common pain points"'),
  ('industries', 'detail_pain_desc', '"We understand the unique challenges this industry faces."'),
  ('industries', 'detail_modules_badge', '"Modules"'),
  ('industries', 'detail_modules_title', '"Recommended modules"'),
  ('industries', 'detail_modules_desc', '"The Marmidon modules most relevant to this industry."'),
  ('industries', 'detail_stat_note', '"Typical results achieved by organisations in this sector after deploying Marmidon ERP."')
ON CONFLICT (section, content_key) DO NOTHING;
