-- CMS coverage gaps: navigation, demo modal, about badges, story detail labels, platform arch headings

INSERT INTO site_content (section, content_key, content_value) VALUES
  ('homepage', 'demo_experience_badge', '"Demo Experience"'::jsonb),
  ('homepage', 'demo_title', '"See HYSYS in action"'::jsonb),
  ('homepage', 'demo_desc', '"Watch a concise product demo to understand how our CRM platform accelerates sales, service, and marketing across teams."'::jsonb),
  ('homepage', 'demo_what_youll_see', '"What you''ll see"'::jsonb),
  ('homepage', 'demo_cta_label', '"Start your free trial"'::jsonb),
  ('homepage', 'platform_arch_headless_left', '"MCPs · APIs · Experience Layer · Identity"'::jsonb),
  ('homepage', 'platform_arch_headless_title', '"Headless 360"'::jsonb),
  ('homepage', 'platform_arch_headless_right', '"Access & Authorization · Compliance · Governance"'::jsonb),
  ('homepage', 'platform_arch_customer360_title', '"Customer 360"'::jsonb),
  ('homepage', 'platform_arch_customer360_tag', '"System of record"'::jsonb),
  ('homepage', 'platform_arch_data360_title', '"Data 360"'::jsonb),
  ('homepage', 'platform_arch_data360_tag', '"System of context"'::jsonb),
  ('homepage', 'platform_arch_trust_layer_label', '"🛡️  AI Trust Layer"'::jsonb),
  ('homepage', 'platform_arch_ask_agentforce', '"🤖 Ask Agentforce"'::jsonb),
  ('navigation', 'nav_products_label', '"Products"'::jsonb),
  ('navigation', 'nav_products_tagline', '"Six powerful clouds. One unified platform."'::jsonb),
  ('navigation', 'nav_view_all', '"View all"'::jsonb),
  ('navigation', 'nav_contact_label', '"Contact"'::jsonb),
  ('navigation', 'nav_signup_label', '"Sign up"'::jsonb),
  ('navigation', 'nav_search_placeholder', '"Search products, industries…"'::jsonb),
  ('navigation', 'nav_mobile_menu_title', '"Menu"'::jsonb),
  ('navigation', 'nav_mobile_menu_subtitle', '"Explore HYSYS products & services"'::jsonb),
  ('navigation', 'nav_mobile_search_placeholder', '"Search…"'::jsonb),
  ('navigation', 'nav_language_active_label', '"Active"'::jsonb),
  ('about', 'hero_badge_label', '"About Us"'::jsonb),
  ('about', 'hero_cta_primary', '"Get in Touch"'::jsonb),
  ('about', 'hero_cta_secondary', '"Start Free Trial"'::jsonb),
  ('about', 'mission_badge', '"Our Mission"'::jsonb),
  ('about', 'mission_cta', '"Join our journey"'::jsonb),
  ('about', 'values_badge', '"What We Stand For"'::jsonb),
  ('about', 'values_subtitle', '"The principles that guide everything we do."'::jsonb),
  ('about', 'leadership_badge', '"The Team"'::jsonb),
  ('about', 'leadership_subtitle', '"World-class leaders driving HYSYS forward."'::jsonb),
  ('about', 'journey_badge', '"Our Journey"'::jsonb),
  ('about', 'cta_secondary_button', '"Start Free Trial"'::jsonb),
  ('stories', 'stories_list_hero_cta_primary', '"Read Stories"'::jsonb),
  ('stories', 'stories_list_hero_cta_secondary', '"Contact Sales"'::jsonb),
  ('stories', 'featured_badge', '"Featured Stories"'::jsonb),
  ('stories', 'detail_subtitle', '"Success Story"'::jsonb),
  ('stories', 'detail_challenge_heading', '"The Challenge"'::jsonb),
  ('stories', 'detail_solution_heading', '"The Solution"'::jsonb),
  ('stories', 'detail_hero_primary_cta', '"Contact Sales"'::jsonb),
  ('stories', 'detail_hero_secondary_cta', '"View All Stories"'::jsonb),
  ('stories', 'detail_cta_title', '"Ready to write your success story?"'::jsonb),
  ('stories', 'detail_cta_desc', '"Join 150,000+ businesses achieving remarkable results with HYSYS."'::jsonb),
  ('stories', 'detail_cta_primary', '"Start Free Trial"'::jsonb),
  ('stories', 'detail_cta_secondary', '"More Stories"'::jsonb)
ON CONFLICT (section, content_key) DO UPDATE SET content_value = EXCLUDED.content_value;
