-- Phase 2 CMS sections: company, partners, partner_apply, careers, team, legal

INSERT INTO public.site_content (section, content_key, content_value) VALUES
  ('company', 'company_title', '"Marmidon Global Solutions"'),
  ('company', 'company_desc', '"We build technology that empowers businesses across Africa and the world to grow, automate, and transform."'),
  ('company', 'company_hero_badge', '"Company"'),
  ('company', 'company_stats_title', '"Marmidon by the numbers"'),
  ('company', 'company_card_link_label', '"Learn more"'),
  ('company', 'cta_title', '"Ready to see Marmidon in action?"'),
  ('company', 'cta_desc', '"Book a personalised demo tailored to your modules and industry."'),
  ('company', 'cta_button', '"Request a Demo"'),
  ('partners', 'partners_title', '"Grow with the Marmidon ecosystem"'),
  ('partners', 'partners_desc', '"Join a global network of partners building, selling, and delivering Marmidon solutions."'),
  ('partners', 'partners_hero_badge', '"Partners"'),
  ('partners', 'partners_cta', '"Become a partner"'),
  ('partners', 'partners_programs_badge', '"Programmes"'),
  ('partners', 'partners_programs_title', '"Partner programmes"'),
  ('partners', 'partners_programs_desc', '"Find the programme that fits your business model and goals."'),
  ('partners', 'partners_benefits_badge', '"Benefits"'),
  ('partners', 'partners_benefits_title', '"Why partner with Marmidon?"'),
  ('partners', 'partners_benefits_desc', '"Access resources, training, and revenue opportunities."'),
  ('partners', 'cta_title', '"Ready to join the Marmidon partner ecosystem?"'),
  ('partners', 'cta_desc', '"Apply today or speak with our partnerships team about programme fit."'),
  ('partners', 'cta_button', '"Apply to become a partner"'),
  ('partners', 'cta_secondary_button', '"Talk to partnerships team"'),
  ('partner_apply', 'apply_hero_badge', '"Partner Application"'),
  ('partner_apply', 'apply_title', '"Become a Marmidon partner"'),
  ('partner_apply', 'apply_desc', '"Fill out the form below and our partnerships team will reach out within 5 business days."'),
  ('partner_apply', 'form_first_name_label', '"First name *"'),
  ('partner_apply', 'form_last_name_label', '"Last name *"'),
  ('partner_apply', 'form_email_label', '"Work email *"'),
  ('partner_apply', 'form_company_label', '"Company name *"'),
  ('partner_apply', 'form_website_label', '"Company website"'),
  ('partner_apply', 'form_program_label', '"Partner programme *"'),
  ('partner_apply', 'form_message_label', '"Tell us about your business *"'),
  ('partner_apply', 'form_submit_label', '"Submit application"'),
  ('partner_apply', 'form_submitting_label', '"Submitting…"'),
  ('partner_apply', 'success_title', '"Application submitted"'),
  ('partner_apply', 'success_desc', '"Thank you for your interest in partnering with Marmidon. Our partnerships team will review your application and get back to you within 5 business days."'),
  ('partner_apply', 'success_back_label', '"Back to home"'),
  ('careers', 'careers_title', '"Join the team building the future"'),
  ('careers', 'careers_desc', '"At Marmidon, we are building enterprise software that empowers businesses across Africa and beyond. Come grow with us."'),
  ('careers', 'careers_hero_badge', '"Careers"'),
  ('careers', 'careers_cta', '"View open roles"'),
  ('careers', 'careers_values_badge', '"Why us?"'),
  ('careers', 'careers_values_title', '"Life at Marmidon"'),
  ('careers', 'careers_values_desc', '"We are building a culture where people do their best work."'),
  ('careers', 'careers_roles_badge', '"Openings"'),
  ('careers', 'careers_roles_title', '"Open roles"'),
  ('careers', 'careers_roles_desc', '"Find your next opportunity at Marmidon."'),
  ('careers', 'careers_apply_label', '"Apply"'),
  ('careers', 'cta_title', '"Ready to see Marmidon in action?"'),
  ('careers', 'cta_desc', '"Book a personalised demo tailored to your modules and industry."'),
  ('careers', 'cta_button', '"Request a Demo"'),
  ('team', 'team_hero_badge', '"Team"'),
  ('team', 'team_title', '"Our leadership team"'),
  ('team', 'team_desc', '"Meet the people driving innovation at Marmidon."'),
  ('team', 'team_back_label', '"Back to Company"'),
  ('team', 'cta_title', '"Ready to see Marmidon in action?"'),
  ('team', 'cta_desc', '"Book a personalised demo tailored to your modules and industry."'),
  ('team', 'cta_button', '"Request a Demo"'),
  ('legal', 'privacy_hero_badge', '"Privacy Statement"'),
  ('legal', 'privacy_hero_title', '"Privacy Policy"'),
  ('legal', 'privacy_hero_subtitle', '"Data protection & trust"'),
  ('legal', 'privacy_hero_desc', '"Learn how we collect, safeguard, and use your information responsibly."'),
  ('legal', 'privacy_hero_cta', '"Contact Privacy Team"'),
  ('legal', 'terms_hero_badge', '"Terms of Service"'),
  ('legal', 'terms_hero_title', '"Terms of Service"'),
  ('legal', 'terms_hero_subtitle', '"Legal terms & usage policies"'),
  ('legal', 'terms_hero_desc', '"Review the rules that govern access to our platform, services, and website."'),
  ('legal', 'terms_hero_cta', '"Contact Legal"'),
  ('legal', 'cookies_hero_badge', '"Cookie Policy"'),
  ('legal', 'cookies_hero_title', '"Cookie Policy"'),
  ('legal', 'cookies_hero_subtitle', '"How we use cookies"'),
  ('legal', 'cookies_hero_desc', '"Understand how Marmidon uses cookies and similar technologies on our website."'),
  ('legal', 'cookies_hero_cta', '"Contact Us"')
ON CONFLICT (section, content_key) DO NOTHING;
