-- Phase 1 CMS sections: pricing, resources, blog, guides, faq_page

INSERT INTO public.site_content (section, content_key, content_value) VALUES
  ('pricing', 'pricing_title', '"ERP pricing that scales with you"'),
  ('pricing', 'pricing_desc', '"Choose the modules and deployment model you need. Every plan starts with a personalised demo and quote."'),
  ('pricing', 'pricing_hero_badge', '"Pricing"'),
  ('pricing', 'pricing_hero_cta', '"Request a Demo"'),
  ('pricing', 'pricing_popular_label', '"Most Popular"'),
  ('pricing', 'pricing_enterprise_title', '"Need a custom solution?"'),
  ('pricing', 'pricing_enterprise_desc', '"Talk to our team about volume discounts, custom integrations, and dedicated support."'),
  ('pricing', 'pricing_contact_cta', '"Contact Sales"'),
  ('pricing', 'pricing_faq_title', '"Frequently asked questions"'),
  ('pricing', 'pricing_faq_desc', '"Everything you need to know about our pricing and plans."'),
  ('resources', 'resources_title', '"Learn, explore, and grow"'),
  ('resources', 'resources_desc', '"Access a wealth of knowledge to help you get the most out of the Marmidon platform."'),
  ('resources', 'resources_hero_badge', '"Resources"'),
  ('resources', 'resources_card_link_label', '"Explore"'),
  ('blog', 'blog_title', '"Marmidon blog"'),
  ('blog', 'blog_desc', '"ERP insights, implementation guides, and stories from the team."'),
  ('blog', 'blog_hero_badge', '"Blog"'),
  ('blog', 'blog_read_more_label', '"Read more"'),
  ('guides', 'guides_title', '"Guides & whitepapers"'),
  ('guides', 'guides_desc', '"In-depth resources to help you make informed decisions about your technology strategy."'),
  ('guides', 'guides_hero_badge', '"Guides"'),
  ('guides', 'guides_download_label', '"Download"'),
  ('guides', 'download_modal_desc', '"Enter your work email to receive this guide."'),
  ('guides', 'download_success_title', '"Download link sent"'),
  ('guides', 'download_success_desc', '"Check your inbox for the guide. Our team will follow up with the PDF shortly."'),
  ('guides', 'download_button_label', '"Get the guide"'),
  ('faq_page', 'faq_title', '"Frequently asked questions"'),
  ('faq_page', 'faq_desc', '"Quick answers about Marmidon ERP modules, demos, pricing, and support."'),
  ('faq_page', 'faq_hero_badge', '"FAQs"'),
  ('faq_page', 'faq_search_placeholder', '"Search FAQs…"')
ON CONFLICT (section, content_key) DO NOTHING;
