/** Central CMS configuration — single source of truth for the Content Manager */

export const PREVIEW_PATHS: Record<string, string> = {
  homepage: '/',
  about: '/company/about',
  products: '/products',
  industries: '/solutions',
  events: '/events',
  contact: '/contact',
  stories: '/customers',
  documentation: '/documentation',
  pricing: '/pricing',
  resources: '/resources',
  blog: '/resources/blog',
  guides: '/resources/guides',
  faq_page: '/resources/faqs',
  company: '/company',
  partners: '/partners',
  partner_apply: '/partners/apply',
  careers: '/company/careers',
  team: '/company/team',
  architecture: '/company/architecture',
  integrations: '/company/integrations',
  security: '/company/security',
  support: '/company/support',
  accessibility_page: '/legal/accessibility',
  legal: '/legal/privacy',
  demo_request: '/request-a-demo',
  navigation: '/',
  global: '/',
};

export const ICON_OPTIONS = [
  'Users', 'Shield', 'Zap', 'BarChart3', 'Cloud', 'ShoppingCart', 'Globe', 'Award',
  'Heart', 'Building2', 'TrendingUp', 'Sparkles', 'GraduationCap', 'Landmark',
  'Cpu', 'Factory', 'BookOpen', 'FileText', 'PlayCircle', 'Phone', 'Mail',
];

export interface FieldMeta {
  label: string;
  hint?: string;
  type?: 'text' | 'textarea' | 'url' | 'image' | 'number' | 'icon';
}

export const FIELD_META: Record<string, FieldMeta> = {
  hero_title: { label: 'Main Headline', type: 'text' },
  hero_subtitle: { label: 'Sub Headline', type: 'text' },
  hero_desc: { label: 'Intro Paragraph', type: 'textarea' },
  hero_cta: { label: 'Primary Button Text', type: 'text' },
  hero_cta_secondary: { label: 'Secondary Button Text', type: 'text' },
  productsTitle: { label: 'Page Title', hint: 'Large heading on the Products page', type: 'text' },
  productsDesc: { label: 'Page Description', type: 'textarea' },
  industriesTitle: { label: 'Page Title', type: 'text' },
  industriesDesc: { label: 'Page Description', type: 'textarea' },
  contactTitle: { label: 'Page Title', type: 'text' },
  contactDesc: { label: 'Page Description', type: 'textarea' },
  customerStoriesTitle: { label: 'Page Title', type: 'text' },
  customerStoriesDesc: { label: 'Page Description', type: 'textarea' },
  getInTouch: { label: 'Contact Sidebar Title', type: 'text' },
  sendUsMessage: { label: 'Form Section Title', type: 'text' },
  phone_numbers: { label: 'Phone Number(s)', hint: 'One per line', type: 'textarea' },
  email_address: { label: 'Email Address', type: 'text' },
  office_address: { label: 'Office Address', type: 'textarea' },
  business_hours: { label: 'Business Hours', type: 'textarea' },
  shareYourStory: { label: 'Bottom CTA Title', type: 'text' },
  shareYourStoryDesc: { label: 'Bottom CTA Description', type: 'textarea' },
  contactUsBtn: { label: 'Bottom CTA Button', type: 'text' },
  video_url: { label: 'Demo Video URL', hint: 'YouTube embed URL', type: 'url' },
  platform_intro_badge: { label: 'Badge Label', type: 'text' },
  platform_intro_title: { label: 'Section Title', type: 'text' },
  platform_intro_desc: { label: 'Section Description', type: 'textarea' },
  product_section_title: { label: 'Products Section Title', type: 'text' },
  product_section_desc: { label: 'Products Section Description', type: 'textarea' },
  features_section_title: { label: 'Features Section Title', type: 'text' },
  features_section_desc: { label: 'Features Section Description', type: 'textarea' },
  stats_modules: { label: 'Stat 1 — Value (ERP modules)', type: 'text' },
  stats_modules_label: { label: 'Stat 1 — Label', type: 'text' },
  stats_sectors: { label: 'Stat 2 — Value (industry sectors)', type: 'text' },
  stats_sectors_label: { label: 'Stat 2 — Label', type: 'text' },
  stats_platform: { label: 'Stat 3 — Value (unified platform)', type: 'text' },
  stats_platform_label: { label: 'Stat 3 — Label', type: 'text' },
  stats_integrations: { label: 'Stat 4 — Value (uptime SLA)', type: 'text' },
  stats_integrations_label: { label: 'Stat 4 — Label', type: 'text' },
  mission_title: { label: 'Mission Title', type: 'text' },
  mission_text_1: { label: 'Mission Paragraph 1', type: 'textarea' },
  mission_text_2: { label: 'Mission Paragraph 2', type: 'textarea' },
  values_title: { label: 'Values Section Title', type: 'text' },
  leadership_title: { label: 'Leadership Section Title', type: 'text' },
  journey_title: { label: 'Journey Section Title', type: 'text' },
  stats_badge: { label: 'Stats Badge Text', type: 'text' },
  newsletter_title: { label: 'Newsletter Title', type: 'text' },
  newsletter_desc: { label: 'Newsletter Description', type: 'textarea' },
  cta_title: { label: 'Call-to-Action Title', type: 'text' },
  cta_desc: { label: 'Call-to-Action Description', type: 'textarea' },
  cta_button: { label: 'Call-to-Action Button', type: 'text' },
  eventsTitle: { label: 'Page Title', type: 'text' },
  eventsDesc: { label: 'Page Description', type: 'textarea' },
  events_section_title: { label: 'Events Section Title', type: 'text' },
  events_section_desc: { label: 'Events Section Description', type: 'textarea' },
  trusted_by_label: { label: 'Trusted By Label', type: 'text' },
  get_started_badge: { label: 'Get Started Badge', type: 'text' },
  get_started_title_1: { label: 'Get Started Title Line 1', type: 'text' },
  get_started_title_2: { label: 'Get Started Title Line 2', type: 'text' },
  get_started_title_3: { label: 'Get Started Title Line 3', type: 'text' },
  get_started_button: { label: 'Get Started Button', type: 'text' },
  get_started_footnote: { label: 'Get Started Footnote', type: 'text' },
  products_grid_title: { label: 'Product Grid Title', type: 'text' },
  products_grid_desc: { label: 'Product Grid Description', type: 'textarea' },
  products_hero_badge: { label: 'Page Hero Badge', type: 'text' },
  products_grid_badge: { label: 'Grid Badge', type: 'text' },
  industries_hero_badge: { label: 'Hero Badge', type: 'text' },
  industries_grid_badge: { label: 'Grid Badge', type: 'text' },
  industries_grid_title: { label: 'Industry Grid Title', type: 'text' },
  industries_grid_desc: { label: 'Industry Grid Description', type: 'textarea' },
  carousel_badge: { label: 'Carousel Badge', type: 'text' },
  carousel_title: { label: 'Carousel Title', type: 'text' },
  carousel_desc: { label: 'Carousel Description', type: 'textarea' },
  hero_trust_badges: { label: 'Hero Trust Badges', hint: 'JSON array of {id, icon, text}', type: 'textarea' },
  platform_arch_badge: { label: 'Architecture Badge', type: 'text' },
  platform_arch_title: { label: 'Architecture Title', type: 'text' },
  platform_arch_desc: { label: 'Architecture Description', type: 'textarea' },
  platform_arch_caption: { label: 'Architecture Caption', type: 'text' },
  ai_business_title: { label: 'AI Section Title', type: 'text' },
  ai_business_desc: { label: 'AI Section Description', type: 'textarea' },
  ai_business_video_url: { label: 'AI Section Video URL', hint: 'YouTube watch or embed URL', type: 'url' },
  ai_business_pricing: { label: 'AI Pricing Note', type: 'text' },
  ai_business_cta_primary: { label: 'AI Primary Button', type: 'text' },
  ai_business_cta_secondary: { label: 'AI Secondary Button', type: 'text' },
  agentforce_stat_value: { label: 'Counter Value', type: 'text' },
  agentforce_stat_label: { label: 'Counter Label', type: 'textarea' },
  customer_proof_video_url: { label: 'Customer Proof Video URL', hint: 'YouTube watch or embed URL', type: 'url' },
  agentforce_title: { label: 'Customer Proof Title', type: 'text' },
  agentforce_desc: { label: 'Customer Proof Description', type: 'textarea' },
  agentforce_cta_primary: { label: 'Customer Proof Primary Button', type: 'text' },
  agentforce_cta_secondary: { label: 'Customer Proof Secondary Button', type: 'text' },
  homepage_industries_title: { label: 'Industries Strip Title', type: 'text' },
  homepage_industries_desc: { label: 'Industries Strip Description', type: 'textarea' },
  analyst_section_title: { label: 'Analyst Section Title', type: 'text' },
  agentblazer_badge: { label: 'Agentblazer Badge', type: 'text' },
  agentblazer_title: { label: 'Agentblazer Title', type: 'text' },
  agentblazer_desc: { label: 'Agentblazer Description', type: 'textarea' },
  agentblazer_cta: { label: 'Agentblazer Button', type: 'text' },
  core_values_title: { label: 'Core Values Title', type: 'text' },
  core_values_desc: { label: 'Core Values Description', type: 'textarea' },
  core_values_cta_primary: { label: 'Core Values Primary Button', type: 'text' },
  core_values_cta_secondary: { label: 'Core Values Secondary Button', type: 'text' },
  ai_success_title: { label: 'AI Success Title', type: 'text' },
  products_suite_badge: { label: 'Suite Badge', type: 'text' },
  products_suite_title: { label: 'Suite Title', type: 'text' },
  products_suite_desc: { label: 'Suite Description', type: 'textarea' },
  spotlight_badge: { label: 'Spotlight Badge', type: 'text' },
  spotlight_title: { label: 'Spotlight Title', type: 'text' },
  spotlight_desc: { label: 'Spotlight Description', type: 'textarea' },
  spotlight_product_name: { label: 'Featured Product Name', type: 'text' },
  spotlight_product_desc: { label: 'Featured Product Description', type: 'textarea' },
  spotlight_benefit_1_title: { label: 'Benefit 1 Title', type: 'text' },
  spotlight_benefit_1_desc: { label: 'Benefit 1 Description', type: 'textarea' },
  spotlight_benefit_2_title: { label: 'Benefit 2 Title', type: 'text' },
  spotlight_benefit_2_desc: { label: 'Benefit 2 Description', type: 'textarea' },
  detail_features_badge: { label: 'Features Badge', type: 'text' },
  detail_features_title: { label: 'Features Title', type: 'text' },
  detail_features_desc: { label: 'Features Description', type: 'textarea' },
  detail_cta_title: { label: 'Detail CTA Title', hint: 'Use {{name}} for product/industry name', type: 'text' },
  detail_cta_desc: { label: 'Detail CTA Description', hint: 'Use {{name}} for product/industry name', type: 'textarea' },
  detail_cta_button: { label: 'Detail CTA Primary Button', type: 'text' },
  detail_cta_secondary: { label: 'Detail CTA Secondary Button', type: 'text' },
  stat1_value: { label: 'Stat 1 Value', type: 'text' },
  stat1_label: { label: 'Stat 1 Label', type: 'text' },
  stat2_value: { label: 'Stat 2 Value', type: 'text' },
  stat2_label: { label: 'Stat 2 Label', type: 'text' },
  accent: { label: 'Gradient Classes', type: 'text' },
  bg: { label: 'Background Gradient', type: 'text' },
  tag: { label: 'Tag Label', type: 'text' },
  desc: { label: 'Card Description', type: 'textarea' },
  faq_section_title: { label: 'FAQ Section Title', type: 'text' },
  featured_section_title: { label: 'Featured Stories Title', type: 'text' },
  featured_section_desc: { label: 'Featured Stories Description', type: 'textarea' },
  events_highlights_title: { label: 'Highlights Section Title', type: 'text' },
  sidebar_title: { label: 'Sidebar Title', type: 'text' },
  sidebar_desc: { label: 'Sidebar Description', type: 'textarea' },
  trial_title: { label: 'Trial Box Title', type: 'text' },
  trial_desc: { label: 'Trial Box Description', type: 'textarea' },
  trial_button: { label: 'Trial Box Button', type: 'text' },
  hero_badge: { label: 'Hero Badge', type: 'text' },
  search_placeholder: { label: 'Search Placeholder', type: 'text' },
  text: { label: 'Bullet Text', type: 'textarea' },
  articles: { label: 'Articles', hint: 'Separate with commas', type: 'textarea' },
  footer_tagline: { label: 'Footer Tagline', type: 'text' },
  support_email: { label: 'Support Email', type: 'text' },
  support_phone: { label: 'Support Phone', type: 'text' },
  pricing_title: { label: 'Page Title', type: 'text' },
  pricing_desc: { label: 'Page Description', type: 'textarea' },
  pricing_hero_badge: { label: 'Hero Badge', type: 'text' },
  pricing_hero_cta: { label: 'Hero CTA Button', type: 'text' },
  pricing_enterprise_title: { label: 'Enterprise Box Title', type: 'text' },
  pricing_enterprise_desc: { label: 'Enterprise Box Description', type: 'textarea' },
  pricing_contact_cta: { label: 'Enterprise Contact Button', type: 'text' },
  pricing_faq_title: { label: 'Pricing FAQ Title', type: 'text' },
  pricing_faq_desc: { label: 'Pricing FAQ Description', type: 'textarea' },
  pricing_popular_label: { label: 'Most Popular Badge', type: 'text' },
  resources_title: { label: 'Page Title', type: 'text' },
  resources_desc: { label: 'Page Description', type: 'textarea' },
  resources_hero_badge: { label: 'Hero Badge', type: 'text' },
  resources_card_link_label: { label: 'Card Link Label', type: 'text' },
  blog_title: { label: 'Page Title', type: 'text' },
  blog_desc: { label: 'Page Description', type: 'textarea' },
  blog_hero_badge: { label: 'Hero Badge', type: 'text' },
  blog_read_more_label: { label: 'Read More Label', type: 'text' },
  guides_title: { label: 'Page Title', type: 'text' },
  guides_desc: { label: 'Page Description', type: 'textarea' },
  guides_hero_badge: { label: 'Hero Badge', type: 'text' },
  guides_download_label: { label: 'Download Button Label', type: 'text' },
  download_modal_desc: { label: 'Download Modal Description', type: 'textarea' },
  download_success_title: { label: 'Download Success Title', type: 'text' },
  download_success_desc: { label: 'Download Success Description', type: 'textarea' },
  download_button_label: { label: 'Download Submit Button', type: 'text' },
  faq_title: { label: 'Page Title', type: 'text' },
  faq_desc: { label: 'Page Description', type: 'textarea' },
  faq_hero_badge: { label: 'Hero Badge', type: 'text' },
  faq_search_placeholder: { label: 'Search Placeholder', type: 'text' },
  category: { label: 'FAQ Category', type: 'text' },
  period: { label: 'Price Period Suffix', type: 'text' },
  tier_highlight: { label: 'Featured Tier (true/false)', type: 'text' },
  pages: { label: 'Page Count Label', type: 'text' },
  body: { label: 'Article Body', type: 'textarea' },
  excerpt: { label: 'Excerpt', type: 'textarea' },
  page_eyebrow: { label: 'Page Eyebrow', hint: 'Company name shown above page titles', type: 'text' },
  page_subtitle_suffix: { label: 'Detail Page Subtitle', hint: 'Short line under product/industry names', type: 'text' },
  card_footer_label: { label: 'Card Footer Link', hint: 'Learn more text on product and industry cards', type: 'text' },
  products_hero_cta_primary: { label: 'Hero Primary Button', type: 'text' },
  products_hero_cta_secondary: { label: 'Hero Secondary Button', type: 'text' },
  spotlight_featured_label: { label: 'Spotlight Featured Label', type: 'text' },
  detail_hero_secondary_cta: { label: 'Detail Hero Secondary Button', type: 'text' },
  industries_hero_cta_primary: { label: 'Hero Primary Button', type: 'text' },
  industries_hero_cta_secondary: { label: 'Hero Secondary Button', type: 'text' },
  industries_list_cta_secondary: { label: 'List Page CTA Secondary', type: 'text' },
  detail_hero_primary_cta: { label: 'Detail Hero Primary Button', type: 'text' },
  homepage_industries_link_label: { label: 'Industry Card Link', type: 'text' },
  homepage_industries_cta: { label: 'Explore All Industries Button', type: 'text' },
  ai_success_title: { label: 'AI Success Section Title', type: 'text' },
  ai_success_card_link_label: { label: 'AI Success Card Link', type: 'text' },
  ai_business_pricing: { label: 'AI Pricing Note', type: 'text' },
  homepage_resources_badge: { label: 'Resources Teaser Badge', type: 'text' },
  homepage_resources_title: { label: 'Resources Teaser Title', type: 'text' },
  homepage_resources_desc: { label: 'Resources Teaser Description', type: 'textarea' },
  homepage_resources_cta: { label: 'Resources Teaser CTA Button', type: 'text' },
  explore_all_products_label: { label: 'Explore Products Button', type: 'text' },
  demo_experience_badge: { label: 'Demo Modal Badge', type: 'text' },
  demo_title: { label: 'Demo Modal Title', type: 'text' },
  demo_desc: { label: 'Demo Modal Description', type: 'textarea' },
  demo_what_youll_see: { label: 'Demo Bullets Heading', type: 'text' },
  demo_cta_label: { label: 'Demo Modal CTA Button', type: 'text' },
  nav_products_label: { label: 'Products Menu Label', type: 'text' },
  nav_products_tagline: { label: 'Products Mega-menu Tagline', type: 'text' },
  nav_view_all: { label: 'View All Products Link', type: 'text' },
  nav_contact_label: { label: 'Contact Link', type: 'text' },
  nav_signup_label: { label: 'Sign Up Button', type: 'text' },
  nav_search_placeholder: { label: 'Search Placeholder', type: 'text' },
  nav_mobile_menu_title: { label: 'Mobile Menu Title', type: 'text' },
  nav_mobile_menu_subtitle: { label: 'Mobile Menu Subtitle', type: 'text' },
  nav_mobile_search_placeholder: { label: 'Mobile Search Placeholder', type: 'text' },
  nav_language_active_label: { label: 'Active Language Badge', type: 'text' },
  label: { label: 'Link Label', type: 'text' },
  labelKey: { label: 'i18n Key (fallback)', type: 'text' },
  path: { label: 'Link Path', type: 'text' },
  sub: { label: 'Subtitle', type: 'text' },
  brand: { label: 'Brand Name', type: 'text' },
  items: { label: 'Tags / Items', hint: 'Separate with commas', type: 'textarea' },
  hero_badge_label: { label: 'Hero Badge Text', type: 'text' },
  hero_cta_primary: { label: 'Hero Primary Button', type: 'text' },
  mission_badge: { label: 'Mission Section Badge', type: 'text' },
  mission_cta: { label: 'Mission CTA Button', type: 'text' },
  values_badge: { label: 'Values Section Badge', type: 'text' },
  values_subtitle: { label: 'Values Section Subtitle', type: 'textarea' },
  leadership_badge: { label: 'Leadership Section Badge', type: 'text' },
  leadership_subtitle: { label: 'Leadership Section Subtitle', type: 'textarea' },
  journey_badge: { label: 'Journey Section Badge', type: 'text' },
  accessibility_hero_badge: { label: 'Accessibility Hero Badge', type: 'text' },
  accessibility_hero_title: { label: 'Accessibility Hero Title', type: 'text' },
  accessibility_hero_subtitle: { label: 'Accessibility Hero Subtitle', type: 'text' },
  accessibility_hero_desc: { label: 'Accessibility Hero Description', type: 'textarea' },
  arch_hero_badge: { label: 'Architecture Hero Badge', type: 'text' },
  arch_hero_title: { label: 'Architecture Hero Title', type: 'text' },
  arch_hero_subtitle: { label: 'Architecture Hero Subtitle', type: 'text' },
  arch_hero_desc: { label: 'Architecture Hero Description', type: 'textarea' },
  arch_hero_cta: { label: 'Architecture Hero Primary Button', type: 'text' },
  arch_hero_secondary: { label: 'Architecture Hero Secondary Button', type: 'text' },
  int_hero_badge: { label: 'Integrations Hero Badge', type: 'text' },
  int_hero_title: { label: 'Integrations Hero Title', type: 'text' },
  int_hero_subtitle: { label: 'Integrations Hero Subtitle', type: 'text' },
  int_hero_desc: { label: 'Integrations Hero Description', type: 'textarea' },
  int_hero_cta: { label: 'Integrations Hero Primary Button', type: 'text' },
  int_hero_secondary: { label: 'Integrations Hero Secondary Button', type: 'text' },
  sec_hero_badge: { label: 'Security Hero Badge', type: 'text' },
  sec_hero_title: { label: 'Security Hero Title', type: 'text' },
  sec_hero_subtitle: { label: 'Security Hero Subtitle', type: 'text' },
  sec_hero_desc: { label: 'Security Hero Description', type: 'textarea' },
  sec_hero_cta: { label: 'Security Hero Primary Button', type: 'text' },
  sec_hero_secondary: { label: 'Security Hero Secondary Button', type: 'text' },
  spt_hero_badge: { label: 'Support Hero Badge', type: 'text' },
  spt_hero_title: { label: 'Support Hero Title', type: 'text' },
  spt_hero_subtitle: { label: 'Support Hero Subtitle', type: 'text' },
  spt_hero_desc: { label: 'Support Hero Description', type: 'textarea' },
  spt_hero_cta: { label: 'Support Hero Primary Button', type: 'text' },
  spt_hero_secondary: { label: 'Support Hero Secondary Button', type: 'text' },
  related_badge: { label: 'Related Stories Badge', type: 'text' },
  related_title: { label: 'Related Stories Title', type: 'text' },
  related_desc: { label: 'Related Stories Description', type: 'textarea' },
  footer_col_connect: { label: 'Footer Connect Column Heading', type: 'text' },
  cta_secondary_button: { label: 'Bottom CTA Secondary Button', type: 'text' },
  platform_arch_headless_left: { label: 'Headless Banner — Left Text', type: 'text' },
  platform_arch_headless_title: { label: 'Headless Banner — Title', type: 'text' },
  platform_arch_headless_right: { label: 'Headless Banner — Right Text', type: 'text' },
  platform_arch_customer360_title: { label: 'Customer 360 Title', type: 'text' },
  platform_arch_customer360_tag: { label: 'Customer 360 Tag', type: 'text' },
  platform_arch_data360_title: { label: 'Data 360 Title', type: 'text' },
  platform_arch_data360_tag: { label: 'Data 360 Tag', type: 'text' },
  platform_arch_trust_layer_label: { label: 'AI Trust Layer Label', type: 'text' },
  platform_arch_ask_agentforce: { label: 'Platform Explore Pill', type: 'text' },
  detail_subtitle: { label: 'Story Detail Subtitle', type: 'text' },
  detail_challenge_heading: { label: 'Challenge Heading', type: 'text' },
  detail_solution_heading: { label: 'Solution Heading', type: 'text' },
  detail_cta_primary: { label: 'Detail Bottom Primary Button', type: 'text' },
  stories_list_hero_cta_primary: { label: 'List Hero Primary Button', type: 'text' },
  stories_list_hero_cta_secondary: { label: 'List Hero Secondary Button', type: 'text' },
  featured_badge: { label: 'Featured Stories Badge', type: 'text' },
  id: { label: 'URL Slug', hint: 'Short ID used in the page URL (e.g. sales-cloud)', type: 'text' },
  key: { label: 'URL Slug', hint: 'Same as id — used in links', type: 'text' },
  title: { label: 'Title', type: 'text' },
  subtitle: { label: 'Subtitle', type: 'text' },
  description: { label: 'Description', type: 'textarea' },
  name: { label: 'Name', type: 'text' },
  company: { label: 'Company', type: 'text' },
  quote: { label: 'Quote', type: 'textarea' },
  role: { label: 'Job Title / Role', type: 'text' },
  bio: { label: 'Biography', type: 'textarea' },
  image: { label: 'Image', type: 'image' },
  thumbnail: { label: 'Thumbnail Image', type: 'image' },
  features: { label: 'Features', hint: 'Separate with commas', type: 'textarea' },
  benefits: { label: 'Benefits', hint: 'Separate with commas', type: 'textarea' },
  stats: { label: 'Stats (JSON)', hint: 'Advanced: JSON array of {label, value}', type: 'textarea' },
  results: { label: 'Results (JSON)', hint: 'JSON array of {label, value}', type: 'textarea' },
  link: { label: 'Link URL', type: 'url' },
  iconName: { label: 'Icon', type: 'icon' },
  color: { label: 'Color Gradient', hint: 'Tailwind classes e.g. from-blue-500 to-blue-700', type: 'text' },
  price: { label: 'Price ($)', type: 'number' },
  date: { label: 'Event Date', type: 'text' },
  highlight: { label: 'Highlight Tag', type: 'text' },
  question: { label: 'Question', type: 'text' },
  answer: { label: 'Answer', type: 'textarea' },
  year: { label: 'Year', type: 'text' },
  event: { label: 'Event Description', type: 'textarea' },
  industry: { label: 'Industry', type: 'text' },
  challenge: { label: 'Challenge', type: 'textarea' },
  solution: { label: 'Solution', type: 'textarea' },
  logo: { label: 'Logo Abbreviation', hint: '2-letter badge e.g. TC', type: 'text' },
  modules: { label: 'Module Count', type: 'number' },
  hours: { label: 'Hours', type: 'number' },
  level: { label: 'Difficulty Level', type: 'text' },
  popular: { label: 'Most Popular?', hint: 'true or false', type: 'text' },
};

export interface SectionGroupDef {
  label: string;
  description?: string;
  keys: string[];
  visual?: 'hero' | 'stats' | 'list' | 'text';
}

export interface CmsSectionDef {
  label: string;
  previewPath: string;
  groups: SectionGroupDef[];
}

export const CMS_SECTIONS: Record<string, CmsSectionDef> = {
  homepage: {
    label: 'Homepage',
    previewPath: '/',
    groups: [
      { label: 'Hero Banner', description: 'The first thing visitors see — headline, intro, and buttons.', keys: ['hero_title', 'hero_subtitle', 'hero_desc', 'hero_cta', 'hero_cta_secondary', 'trusted_by_label'], visual: 'hero' },
      { label: 'Hero Trust Badges', description: 'Small trust lines under the hero buttons.', keys: ['hero_trust_badges'], visual: 'list' },
      { label: 'Stats Bar', description: 'Four Marmidon metrics below the hero (modules, sectors, platform, uptime).', keys: ['stats_modules', 'stats_modules_label', 'stats_sectors', 'stats_sectors_label', 'stats_platform', 'stats_platform_label', 'stats_integrations', 'stats_integrations_label'], visual: 'stats' },
      { label: 'Platform Intro', description: 'The grey section explaining your platform vision.', keys: ['platform_intro_badge', 'platform_intro_title', 'platform_intro_desc'], visual: 'text' },
      { label: 'Product Cards', description: 'Eleven module cards on the homepage. Add an image URL or leave blank for the icon.', keys: ['product_cards'], visual: 'list' },
      { label: 'Features Grid', description: 'Four feature highlights (Lightning Fast, Security, etc.). Shown below product cards.', keys: ['features_section_title', 'features_section_desc', 'features'], visual: 'list' },
      { label: 'Products Section Headings', description: 'Title and subtitle above the product card grid.', keys: ['product_section_title', 'product_section_desc'], visual: 'text' },
      { label: 'Demo Video', description: 'YouTube URL used in the demo modal and video sections.', keys: ['video_url', 'demo_experience_badge', 'demo_title', 'demo_desc', 'demo_what_youll_see', 'demo_cta_label', 'demo_bullets'], visual: 'list' },
      { label: 'Trusted Brands', description: 'Company names scrolling in the trust bar.', keys: ['trusted_brands'], visual: 'list' },
      { label: 'Get Started Banner', description: 'Bottom gradient CTA before the FAQ section.', keys: ['get_started_badge', 'get_started_title_1', 'get_started_title_2', 'get_started_title_3', 'get_started_button', 'get_started_footnote'], visual: 'text' },
      { label: 'Platform Architecture', keys: ['platform_arch_badge', 'platform_arch_title', 'platform_arch_desc', 'platform_arch_caption', 'platform_arch_headless_left', 'platform_arch_headless_title', 'platform_arch_headless_right', 'platform_arch_customer360_title', 'platform_arch_customer360_tag', 'platform_arch_data360_title', 'platform_arch_data360_tag', 'platform_arch_trust_layer_label', 'platform_arch_ask_agentforce', 'platform_arch_agents', 'platform_arch_layers', 'platform_arch_customer360_items', 'platform_arch_data360_items', 'platform_arch_providers'], visual: 'list' },
      { label: 'AI for Business', keys: ['ai_business_title', 'ai_business_desc', 'ai_business_video_url', 'ai_business_pricing', 'ai_business_cta_primary', 'ai_business_cta_secondary'], visual: 'text' },
      { label: 'Customer Proof Stats', keys: ['agentforce_stat_value', 'agentforce_stat_label', 'customer_proof_video_url', 'agentforce_title', 'agentforce_desc', 'agentforce_cta_primary', 'agentforce_cta_secondary'], visual: 'text' },
      { label: 'Resources Teaser', description: '"Latest Insights" section showing the latest 3 blog posts.', keys: ['homepage_resources_badge', 'homepage_resources_title', 'homepage_resources_desc', 'homepage_resources_cta'], visual: 'text' },
      { label: 'Homepage Industries', description: 'Industry cards strip on the homepage.', keys: ['homepage_industries_title', 'homepage_industries_desc', 'homepage_industries_list'], visual: 'list' },
      { label: 'Analyst Reports', keys: ['analyst_section_title', 'analyst_reports'], visual: 'list' },
      { label: 'Agentblazer', keys: ['agentblazer_badge', 'agentblazer_title', 'agentblazer_desc', 'agentblazer_cta'], visual: 'text' },
      { label: 'Core Values Block', keys: ['core_values_title', 'core_values_desc', 'core_values_cta_primary', 'core_values_cta_secondary', 'core_values_tags'], visual: 'list' },
      { label: 'AI Success Cards', keys: ['ai_success_title', 'ai_success_cards', 'ai_success_card_link_label'], visual: 'list' },
      { label: 'Homepage Actions', description: 'Button and link labels on the homepage product/industry sections.', keys: ['explore_all_products_label', 'homepage_industries_link_label', 'homepage_industries_cta'], visual: 'text' },
    ],
  },
  about: {
    label: 'About Us',
    previewPath: '/about',
    groups: [
      { label: 'Page Header', keys: ['hero_badge_label', 'hero_title', 'hero_desc', 'hero_cta_primary', 'hero_cta_secondary'], visual: 'hero' },
      { label: 'Mission', keys: ['mission_badge', 'mission_title', 'mission_text_1', 'mission_text_2', 'mission_bullets', 'mission_cta'], visual: 'list' },
      { label: 'Values Heading', keys: ['values_badge', 'values_title', 'values_subtitle'], visual: 'text' },
      { label: 'Core Values', description: 'Four value cards with icon, title, and description.', keys: ['values'], visual: 'list' },
      { label: 'Leadership Heading', keys: ['leadership_badge', 'leadership_title', 'leadership_subtitle'], visual: 'text' },
      { label: 'Team Members', description: 'Name, role, bio, and photo for each leader.', keys: ['leadership_team'], visual: 'list' },
      { label: 'Company Journey', keys: ['journey_badge', 'journey_title'], visual: 'text' },
      { label: 'Milestones', description: 'Timeline events (year + description).', keys: ['milestones'], visual: 'list' },
      { label: 'Stats Bar', description: 'Four headline metrics below the hero.', keys: ['about_stats'], visual: 'list' },
      { label: 'Stats Badge', keys: ['stats_badge'], visual: 'text' },
      { label: 'Bottom Call-to-Action', keys: ['cta_title', 'cta_desc', 'cta_button', 'cta_secondary_button'], visual: 'text' },
    ],
  },
  products: {
    label: 'Products',
    previewPath: '/products',
    groups: [
      { label: 'Page Header', keys: ['products_hero_badge', 'productsTitle', 'productsDesc'], visual: 'hero' },
      { label: 'Product Grid Headings', description: 'Title and subtitle above the product cards on /products.', keys: ['products_grid_badge', 'products_grid_title', 'products_grid_desc'], visual: 'text' },
      { label: 'Product Suite Section', description: 'Secondary product card grid headings.', keys: ['products_suite_badge', 'products_suite_title', 'products_suite_desc'], visual: 'text' },
      { label: 'Product Spotlight', description: 'Featured product showcase block.', keys: ['spotlight_badge', 'spotlight_title', 'spotlight_desc', 'spotlight_product_name', 'spotlight_product_desc', 'spotlight_benefit_1_title', 'spotlight_benefit_1_desc', 'spotlight_benefit_2_title', 'spotlight_benefit_2_desc'], visual: 'text' },
      { label: 'Product Detail Features', description: 'Headings on individual product pages.', keys: ['detail_features_badge', 'detail_features_title', 'detail_features_desc'], visual: 'text' },
      { label: 'Product Detail Sections', description: 'Section headings on product detail pages.', keys: ['detail_outcomes_badge', 'detail_outcomes_title', 'detail_outcomes_desc', 'detail_integration_title', 'detail_industries_title', 'detail_industries_desc', 'detail_faq_title', 'detail_related_title', 'detail_related_desc'], visual: 'text' },
      { label: 'Product Detail Call-to-Action', description: 'Bottom banner on individual product pages. Use {{name}} for the product name.', keys: ['detail_cta_title', 'detail_cta_desc', 'detail_cta_button', 'detail_cta_secondary'], visual: 'text' },
      { label: 'Page Actions & Labels', description: 'Hero buttons, card links, and spotlight labels on the products pages.', keys: ['products_hero_cta_primary', 'products_hero_cta_secondary', 'spotlight_featured_label', 'detail_hero_primary_cta', 'detail_hero_secondary_cta'], visual: 'text' },
      { label: 'All Products', description: 'Each product card on /products. Fill in Title to override the default label.', keys: ['products_list'], visual: 'list' },
      { label: 'Bottom Call-to-Action', keys: ['cta_title', 'cta_desc', 'cta_button'], visual: 'text' },
    ],
  },
  industries: {
    label: 'Solutions',
    previewPath: '/solutions',
    groups: [
      { label: 'Page Header', keys: ['industriesTitle', 'industriesDesc', 'industries_hero_badge'], visual: 'hero' },
      { label: 'Industry Grid Headings', description: 'Title and subtitle above the industry cards.', keys: ['industries_grid_badge', 'industries_grid_title', 'industries_grid_desc'], visual: 'text' },
      { label: 'Industry Cards', description: 'Each industry sector. Use URL slug as id (e.g. healthcare).', keys: ['industries_list'], visual: 'list' },
      { label: 'Industry Detail Sections', description: 'Section headings on solution detail pages. Use {{name}} for the industry name.', keys: ['detail_helps_badge', 'detail_helps_title', 'detail_helps_desc', 'detail_pain_badge', 'detail_pain_title', 'detail_pain_desc', 'detail_modules_badge', 'detail_modules_title', 'detail_modules_desc', 'detail_stat_note'], visual: 'text' },
      { label: 'Industry Detail Call-to-Action', description: 'Bottom banner on individual industry pages. Use {{name}} for the industry name.', keys: ['detail_cta_title', 'detail_cta_desc', 'detail_cta_button', 'detail_cta_secondary'], visual: 'text' },
      { label: 'Page Actions & Labels', description: 'Hero buttons and card link text on industry pages.', keys: ['industries_hero_cta_primary', 'industries_hero_cta_secondary', 'industries_list_cta_secondary', 'detail_hero_primary_cta', 'detail_hero_secondary_cta'], visual: 'text' },
      { label: 'Bottom Call-to-Action', keys: ['cta_title', 'cta_desc', 'cta_button'], visual: 'text' },
    ],
  },
  events: {
    label: 'Events',
    previewPath: '/events',
    groups: [
      { label: 'Page Header', keys: ['events_hero_badge', 'eventsTitle', 'eventsDesc', 'events_hero_cta_primary', 'events_hero_cta_secondary'], visual: 'hero' },
      { label: 'Events Section', keys: ['events_section_badge', 'events_section_title', 'events_section_desc'], visual: 'text' },
      { label: 'Event Cards', description: 'Upcoming events shown on the Events page.', keys: ['events_list'], visual: 'list' },
      { label: 'Event Highlights', description: 'Bullet points explaining why attendees should join.', keys: ['events_highlights_badge', 'events_highlights_title', 'events_highlights'], visual: 'list' },
      { label: 'Reserve Box', description: 'Gradient call-to-action box beside highlights.', keys: ['cta_title', 'cta_desc', 'cta_button'], visual: 'text' },
      { label: 'Event FAQs', description: 'Questions and answers about events.', keys: ['faq_section_badge', 'faq_section_title', 'faqs'], visual: 'list' },
    ],
  },
  contact: {
    label: 'Contact',
    previewPath: '/contact',
    groups: [
      { label: 'Page Header', keys: ['contact_hero_badge', 'contactTitle', 'contactDesc', 'contact_hero_cta_primary', 'contact_hero_cta_secondary'], visual: 'hero' },
      { label: 'Contact Details', description: 'Phone, email, address, and hours shown in the info cards.', keys: ['getInTouch', 'sendUsMessage', 'phone_numbers', 'email_address', 'office_address', 'business_hours'], visual: 'text' },
      { label: 'Form Sidebar', description: 'Left panel beside the contact form.', keys: ['sidebar_title', 'sidebar_desc', 'trial_title', 'trial_desc', 'trial_button'], visual: 'text' },
      { label: 'Form Labels', keys: ['form_required_note', 'form_first_name_label', 'form_last_name_label', 'form_email_label', 'form_phone_label', 'form_company_label', 'form_job_title_label', 'form_interest_label', 'form_message_label', 'form_submit_label', 'form_submitting_label'], visual: 'text' },
      { label: 'Success Message', keys: ['success_title', 'success_desc', 'success_again_label'], visual: 'text' },
    ],
  },
  documentation: {
    label: 'Documentation',
    previewPath: '/documentation',
    groups: [
      { label: 'Page Header', keys: ['hero_badge', 'hero_title', 'hero_subtitle', 'hero_desc', 'hero_cta', 'hero_cta_secondary'], visual: 'hero' },
      { label: 'Search', keys: ['search_placeholder'], visual: 'text' },
      { label: 'Doc Categories', description: 'Documentation category cards with article lists.', keys: ['doc_categories'], visual: 'list' },
      { label: 'Bottom Call-to-Action', keys: ['cta_title', 'cta_desc', 'cta_button'], visual: 'text' },
    ],
  },
  stories: {
    label: 'Customer Stories',
    previewPath: '/customer-stories',
    groups: [
      { label: 'Page Header', keys: ['customerStoriesTitle', 'customerStoriesDesc', 'stories_list_hero_cta_primary', 'stories_list_hero_cta_secondary'], visual: 'hero' },
      { label: 'Stats Bar', description: 'Four metrics shown below the page header.', keys: ['stories_stats'], visual: 'list' },
      { label: 'Featured Section Headings', keys: ['featured_badge', 'featured_section_title', 'featured_section_desc'], visual: 'text' },
      { label: 'Homepage Carousel', description: 'Customer stories video carousel on the homepage.', keys: ['carousel_badge', 'carousel_title', 'carousel_desc'], visual: 'text' },
      { label: 'Success Stories', description: 'Customer case studies. Fill in name, quote, company, and thumbnail image.', keys: ['customer_stories'], visual: 'list' },
      { label: 'Bottom Call-to-Action', keys: ['shareYourStory', 'shareYourStoryDesc', 'contactUsBtn'], visual: 'text' },
      { label: 'Related Stories', description: '"More success stories" section on story detail pages.', keys: ['related_badge', 'related_title', 'related_desc'], visual: 'text' },
      { label: 'Story Detail Page', description: 'Labels on individual customer story pages.', keys: ['detail_subtitle', 'detail_challenge_heading', 'detail_solution_heading', 'detail_hero_primary_cta', 'detail_hero_secondary_cta', 'detail_cta_title', 'detail_cta_desc', 'detail_cta_primary', 'detail_cta_secondary'], visual: 'text' },
    ],
  },
  navigation: {
    label: 'Navigation',
    previewPath: '/',
    groups: [
      { label: 'Mega-menu Labels', description: 'Top-level dropdown titles and taglines.', keys: ['nav_products_label', 'nav_products_tagline', 'nav_solutions_label', 'nav_solutions_tagline', 'nav_resources_label', 'nav_resources_tagline', 'nav_company_label', 'nav_company_tagline', 'nav_view_all'], visual: 'text' },
      { label: 'Header Actions', description: 'Contact, demo, search, and mobile menu labels.', keys: ['nav_contact_sales_label', 'nav_demo_label', 'nav_search_placeholder', 'nav_mobile_menu_title', 'nav_mobile_menu_subtitle', 'nav_mobile_search_placeholder', 'nav_language_active_label'], visual: 'text' },
      { label: 'Flat Nav Links', description: 'Customers, Pricing, Partners in the top bar.', keys: ['nav_customers_label', 'nav_pricing_label', 'nav_partners_label'], visual: 'text' },
      { label: 'Products Dropdown', description: 'Items in the Products mega-menu.', keys: ['nav_products'], visual: 'list' },
      { label: 'Solutions Dropdown', description: 'Industry sectors in the Solutions mega-menu.', keys: ['nav_solutions'], visual: 'list' },
      { label: 'Resources Dropdown', description: 'Items in the Resources mega-menu.', keys: ['nav_resources'], visual: 'list' },
      { label: 'Company Dropdown', description: 'Items in the Company mega-menu.', keys: ['nav_company'], visual: 'list' },
    ],
  },
  pricing: {
    label: 'Pricing',
    previewPath: '/pricing',
    groups: [
      { label: 'Page Header', keys: ['pricing_hero_badge', 'pricing_title', 'pricing_desc', 'pricing_hero_cta'], visual: 'hero' },
      { label: 'Pricing Tiers', description: 'Three plan cards. Set tier_highlight to true for the featured tier.', keys: ['pricing_tiers'], visual: 'list' },
      { label: 'Tier Labels', keys: ['pricing_popular_label'], visual: 'text' },
      { label: 'Enterprise Box', keys: ['pricing_enterprise_title', 'pricing_enterprise_desc', 'pricing_contact_cta'], visual: 'text' },
      { label: 'Pricing FAQs', keys: ['pricing_faq_title', 'pricing_faq_desc', 'pricing_faqs'], visual: 'list' },
      { label: 'Bottom Call-to-Action', keys: ['cta_title', 'cta_desc', 'cta_button'], visual: 'text' },
    ],
  },
  resources: {
    label: 'Resources Hub',
    previewPath: '/resources',
    groups: [
      { label: 'Page Header', keys: ['resources_hero_badge', 'resources_title', 'resources_desc'], visual: 'hero' },
      { label: 'Resource Cards', description: 'Links to blog, guides, FAQs, and documentation.', keys: ['resources_cards'], visual: 'list' },
      { label: 'Card Labels', keys: ['resources_card_link_label'], visual: 'text' },
      { label: 'Newsletter Signup', description: 'Email subscription prompt on resources pages.', keys: ['newsletter_title', 'newsletter_desc'], visual: 'text' },
      { label: 'Bottom Call-to-Action', keys: ['cta_title', 'cta_desc', 'cta_button'], visual: 'text' },
    ],
  },
  blog: {
    label: 'Blog',
    previewPath: '/resources/blog',
    groups: [
      { label: 'Page Header', keys: ['blog_hero_badge', 'blog_title', 'blog_desc'], visual: 'hero' },
      { label: 'Blog Labels', keys: ['blog_read_more_label'], visual: 'text' },
      { label: 'Newsletter Signup', description: 'Email subscription prompt on blog pages.', keys: ['newsletter_title', 'newsletter_desc'], visual: 'text' },
      { label: 'Blog Posts', description: 'Use slug as id (URL path). Body supports paragraphs separated by blank lines.', keys: ['blog_posts'], visual: 'list' },
      { label: 'Bottom Call-to-Action', keys: ['cta_title', 'cta_desc', 'cta_button'], visual: 'text' },
    ],
  },
  guides: {
    label: 'Guides',
    previewPath: '/resources/guides',
    groups: [
      { label: 'Page Header', keys: ['guides_hero_badge', 'guides_title', 'guides_desc'], visual: 'hero' },
      { label: 'Guide Labels', keys: ['guides_download_label'], visual: 'text' },
      { label: 'Guide Downloads', description: 'Whitepapers and PDF resources.', keys: ['guides_list'], visual: 'list' },
      { label: 'Download Modal', keys: ['download_modal_desc', 'download_success_title', 'download_success_desc', 'download_button_label'], visual: 'text' },
      { label: 'Bottom Call-to-Action', keys: ['cta_title', 'cta_desc', 'cta_button'], visual: 'text' },
    ],
  },
  faq_page: {
    label: 'FAQs Page',
    previewPath: '/resources/faqs',
    groups: [
      { label: 'Page Header', keys: ['faq_hero_badge', 'faq_title', 'faq_desc', 'faq_search_placeholder'], visual: 'hero' },
      { label: 'FAQ Items', description: 'Grouped by category on the live page.', keys: ['faq_items'], visual: 'list' },
      { label: 'Bottom Call-to-Action', keys: ['cta_title', 'cta_desc', 'cta_button'], visual: 'text' },
    ],
  },
  company: {
    label: 'Company Hub',
    previewPath: '/company',
    groups: [
      { label: 'Page Header', keys: ['company_hero_badge', 'company_title', 'company_desc'], visual: 'hero' },
      { label: 'Section Cards', description: 'Links to About, Team, Careers, etc.', keys: ['company_sections'], visual: 'list' },
      { label: 'Card Labels', keys: ['company_card_link_label'], visual: 'text' },
      { label: 'Stats Strip', keys: ['company_stats_title', 'company_stats'], visual: 'list' },
      { label: 'Bottom Call-to-Action', keys: ['cta_title', 'cta_desc', 'cta_button'], visual: 'text' },
    ],
  },
  partners: {
    label: 'Partners',
    previewPath: '/partners',
    groups: [
      { label: 'Page Header', keys: ['partners_hero_badge', 'partners_title', 'partners_desc', 'partners_cta'], visual: 'hero' },
      { label: 'Programmes Headings', keys: ['partners_programs_badge', 'partners_programs_title', 'partners_programs_desc'], visual: 'text' },
      { label: 'Partner Programmes', keys: ['partners_programs'], visual: 'list' },
      { label: 'Benefits Headings', keys: ['partners_benefits_badge', 'partners_benefits_title', 'partners_benefits_desc'], visual: 'text' },
      { label: 'Partner Benefits', keys: ['partners_benefits'], visual: 'list' },
      { label: 'Partner Directory', keys: ['partners_list'], visual: 'list' },
      { label: 'Bottom Call-to-Action', keys: ['cta_title', 'cta_desc', 'cta_button', 'cta_secondary_button'], visual: 'text' },
    ],
  },
  partner_apply: {
    label: 'Partner Application',
    previewPath: '/partners/apply',
    groups: [
      { label: 'Page Header', keys: ['apply_hero_badge', 'apply_title', 'apply_desc'], visual: 'hero' },
      { label: 'Form Labels', keys: ['form_first_name_label', 'form_last_name_label', 'form_email_label', 'form_company_label', 'form_website_label', 'form_program_label', 'form_message_label', 'form_submit_label', 'form_submitting_label'], visual: 'text' },
      { label: 'Success Message', keys: ['success_title', 'success_desc', 'success_back_label'], visual: 'text' },
    ],
  },
  careers: {
    label: 'Careers',
    previewPath: '/company/careers',
    groups: [
      { label: 'Page Header', keys: ['careers_hero_badge', 'careers_title', 'careers_desc', 'careers_cta'], visual: 'hero' },
      { label: 'Culture Headings', keys: ['careers_values_badge', 'careers_values_title', 'careers_values_desc'], visual: 'text' },
      { label: 'Culture & Values', keys: ['careers_values'], visual: 'list' },
      { label: 'Roles Headings', keys: ['careers_roles_badge', 'careers_roles_title', 'careers_roles_desc', 'careers_apply_label'], visual: 'text' },
      { label: 'Open Roles', keys: ['open_roles'], visual: 'list' },
      { label: 'Bottom Call-to-Action', keys: ['cta_title', 'cta_desc', 'cta_button'], visual: 'text' },
    ],
  },
  team: {
    label: 'Team',
    previewPath: '/company/team',
    groups: [
      { label: 'Page Header', keys: ['team_hero_badge', 'team_title', 'team_desc', 'team_back_label'], visual: 'hero' },
      { label: 'Bottom Call-to-Action', keys: ['cta_title', 'cta_desc', 'cta_button'], visual: 'text' },
    ],
  },
  architecture: {
    label: 'Technical Architecture',
    previewPath: '/company/architecture',
    groups: [
      { label: 'Page Header', keys: ['arch_hero_badge', 'arch_hero_title', 'arch_hero_subtitle', 'arch_hero_desc', 'arch_hero_cta', 'arch_hero_secondary'], visual: 'hero' },
      { label: 'Bottom Call-to-Action', keys: ['cta_title', 'cta_desc', 'cta_button'], visual: 'text' },
    ],
  },
  integrations: {
    label: 'Integrations',
    previewPath: '/company/integrations',
    groups: [
      { label: 'Page Header', keys: ['int_hero_badge', 'int_hero_title', 'int_hero_subtitle', 'int_hero_desc', 'int_hero_cta', 'int_hero_secondary'], visual: 'hero' },
      { label: 'Bottom Call-to-Action', keys: ['cta_title', 'cta_desc', 'cta_button'], visual: 'text' },
    ],
  },
  security: {
    label: 'Security & Compliance',
    previewPath: '/company/security',
    groups: [
      { label: 'Page Header', keys: ['sec_hero_badge', 'sec_hero_title', 'sec_hero_subtitle', 'sec_hero_desc', 'sec_hero_cta', 'sec_hero_secondary'], visual: 'hero' },
      { label: 'Bottom Call-to-Action', keys: ['cta_title', 'cta_desc', 'cta_button'], visual: 'text' },
    ],
  },
  support: {
    label: 'Support & SLAs',
    previewPath: '/company/support',
    groups: [
      { label: 'Page Header', keys: ['spt_hero_badge', 'spt_hero_title', 'spt_hero_subtitle', 'spt_hero_desc', 'spt_hero_cta', 'spt_hero_secondary'], visual: 'hero' },
      { label: 'Bottom Call-to-Action', keys: ['cta_title', 'cta_desc', 'cta_button'], visual: 'text' },
    ],
  },
  accessibility_page: {
    label: 'Accessibility Statement',
    previewPath: '/legal/accessibility',
    groups: [
      { label: 'Page Header', keys: ['accessibility_hero_badge', 'accessibility_hero_title', 'accessibility_hero_subtitle', 'accessibility_hero_desc', 'accessibility_hero_cta'], visual: 'hero' },
    ],
  },
  legal: {
    label: 'Legal Pages',
    previewPath: '/legal/privacy',
    groups: [
      { label: 'Privacy Page Hero', keys: ['privacy_hero_badge', 'privacy_hero_title', 'privacy_hero_subtitle', 'privacy_hero_desc', 'privacy_hero_cta'], visual: 'hero' },
      { label: 'Terms Page Hero', keys: ['terms_hero_badge', 'terms_hero_title', 'terms_hero_subtitle', 'terms_hero_desc', 'terms_hero_cta'], visual: 'hero' },
      { label: 'Cookies Page Hero', keys: ['cookies_hero_badge', 'cookies_hero_title', 'cookies_hero_subtitle', 'cookies_hero_desc', 'cookies_hero_cta'], visual: 'hero' },
    ],
  },
  demo_request: {
    label: 'Demo Request',
    previewPath: '/request-a-demo',
    groups: [
      { label: 'Page Header', keys: ['demo_hero_badge', 'demo_title', 'demo_desc'], visual: 'hero' },
      { label: 'Form Labels', keys: ['form_first_name_label', 'form_last_name_label', 'form_email_label', 'form_company_label', 'form_phone_label', 'form_modules_label', 'form_industry_label', 'form_message_label', 'form_submit_label', 'form_submitting_label'], visual: 'text' },
      { label: 'Success Message', keys: ['success_title', 'success_desc', 'success_back_label'], visual: 'text' },
    ],
  },
  global: {
    label: 'Site-wide',
    previewPath: '/',
    groups: [
      { label: 'Footer Brand', keys: ['footer_brand_name', 'footer_tagline', 'footer_website_url', 'footer_copyright'], visual: 'text' },
      { label: 'Footer & Support', description: 'Contact info shown in the footer and support areas.', keys: ['support_email', 'support_phone'], visual: 'text' },
      { label: 'Footer Column Headings', keys: ['footer_col_products', 'footer_col_solutions', 'footer_col_resources', 'footer_col_company', 'footer_col_connect', 'footer_all_products_label', 'footer_all_solutions_label'], visual: 'text' },
      { label: 'Footer Resource Links', description: 'Links in the Resources column.', keys: ['footer_resources'], visual: 'list' },
      { label: 'Footer Company Links', description: 'Links in the Company column.', keys: ['footer_company'], visual: 'list' },
      { label: 'Footer Legal Links', description: 'Link labels for the legal row in the footer.', keys: ['footer_privacy_label', 'footer_terms_label', 'footer_cookies_label', 'footer_sitemap_label'], visual: 'text' },
      { label: 'Site-wide Labels', description: 'Shared labels used across product cards, detail pages, and heroes.', keys: ['page_eyebrow', 'page_subtitle_suffix', 'card_footer_label'], visual: 'text' },
      { label: 'Homepage FAQ', description: 'FAQ section at the bottom of the homepage.', keys: ['faq_section_title', 'faqs'], visual: 'list' },
    ],
  },
};

/** Preferred field order per array type — direct text fields first */
export const ARRAY_FIELD_ORDER: Record<string, string[]> = {
  product_cards: ['title', 'subtitle', 'description', 'titleKey', 'subtitleKey', 'descriptionKey', 'link', 'image', 'iconName', 'color'],
  features: ['title', 'description', 'titleKey', 'descriptionKey', 'iconName'],
  products_list: ['id', 'key', 'title', 'subtitle', 'description', 'titleKey', 'subtitleKey', 'descriptionKey', 'image', 'features', 'iconName', 'color', 'ctaKey'],
  industries_list: ['id', 'key', 'title', 'subtitle', 'description', 'titleKey', 'subtitleKey', 'descriptionKey', 'image', 'features', 'stats', 'iconName', 'color'],
  events_list: ['id', 'date', 'title', 'description', 'highlight', 'image'],
  events_highlights: ['text'],
  stories_stats: ['value', 'label', 'iconName'],
  doc_categories: ['title', 'description', 'iconName', 'articles', 'image'],
  faqs: ['question', 'answer', 'questionKey', 'answerKey'],
  leadership_team: ['name', 'role', 'bio', 'image'],
  milestones: ['year', 'event', 'eventKey'],
  values: ['title', 'description', 'titleKey', 'descriptionKey', 'iconName', 'image'],
  customer_stories: ['id', 'name', 'title', 'company', 'quote', 'thumbnail', 'image', 'logo', 'industry', 'nameKey', 'industryKey', 'quoteKey', 'challenge', 'solution', 'challengeKey', 'solutionKey', 'results'],
  hero_trust_badges: ['text', 'icon'],
  homepage_industries_list: ['title', 'description', 'link', 'image'],
  analyst_reports: ['tag', 'title', 'stat1_value', 'stat1_label', 'stat2_value', 'stat2_label', 'link', 'image'],
  core_values_tags: [],
  ai_success_cards: ['tag', 'title', 'desc', 'link', 'image'],
  trusted_brands: [],
  demo_bullets: ['text'],
  platform_arch_agents: ['icon', 'title', 'sub'],
  platform_arch_layers: ['icon', 'brand', 'tag', 'accent', 'items'],
  platform_arch_customer360_items: ['icon', 'label'],
  platform_arch_data360_items: ['icon', 'label'],
  platform_arch_providers: ['label'],
  nav_products: ['title', 'desc', 'path', 'iconName', 'accent'],
  nav_links: ['label', 'labelKey', 'path'],
  mission_bullets: ['text'],
  stats: ['value', 'label', 'labelKey'],
  pricing_tiers: ['id', 'name', 'price', 'period', 'desc', 'features', 'cta', 'tier_highlight'],
  pricing_faqs: ['id', 'question', 'answer'],
  resources_cards: ['id', 'title', 'description', 'path', 'iconName', 'accent', 'image'],
  blog_posts: ['id', 'slug', 'title', 'excerpt', 'date', 'author', 'category', 'body', 'image'],
  guides_list: ['id', 'title', 'desc', 'pages', 'type', 'image'],
  faq_items: ['id', 'category', 'question', 'answer'],
  about_stats: ['id', 'value', 'label', 'iconName'],
  company_sections: ['id', 'title', 'description', 'path', 'iconName', 'accent', 'image'],
  company_stats: ['id', 'value', 'label'],
  partners_programs: ['id', 'title', 'desc', 'iconName', 'accent', 'image'],
  partners_benefits: ['id', 'title', 'desc'],
  partners_list: ['id', 'name', 'location', 'program', 'sectors', 'website'],
  careers_values: ['id', 'title', 'desc', 'image'],
  open_roles: ['id', 'title', 'dept', 'location', 'type'],
  nav_solutions: ['id', 'title', 'desc', 'path', 'iconName', 'accent'],
  nav_resources: ['id', 'title', 'desc', 'path', 'iconName', 'accent'],
  nav_company: ['id', 'title', 'desc', 'path', 'iconName', 'accent'],
  footer_resources: ['id', 'title', 'path'],
  footer_company: ['id', 'title', 'path'],
};

export const ARRAY_TEMPLATES: Record<string, Record<string, string>> = {
  product_cards: { title: '', subtitle: '', description: '', titleKey: '', subtitleKey: '', descriptionKey: '', link: '/', image: '', iconName: 'Users', color: 'from-blue-500 to-blue-700' },
  features: { title: '', description: '', titleKey: '', descriptionKey: '', iconName: 'Zap' },
  stats: { value: '', label: '', labelKey: '' },
  products_list: { id: '', title: '', subtitle: '', description: '', image: '', features: '', iconName: 'Shield', color: 'from-blue-500 to-blue-700', ctaKey: '' },
  industries_list: { id: '', title: '', subtitle: '', description: '', image: '', features: '', stats: '', iconName: 'Heart', color: 'from-rose-500 to-pink-600' },
  events_list: { id: '', date: '', title: '', description: '', highlight: '', image: '' },
  events_highlights: { id: '', text: '' },
  stories_stats: { id: '', value: '', label: '', iconName: 'Users' },
  doc_categories: { id: '', title: '', description: '', iconName: 'FileText', articles: '', image: '' },
  faqs: { question: '', answer: '', questionKey: '', answerKey: '' },
  leadership_team: { name: '', role: '', bio: '', image: '' },
  milestones: { year: '', event: '', eventKey: '' },
  values: { title: '', description: '', titleKey: '', descriptionKey: '', iconName: 'Users', image: '' },
  customer_stories: { id: '', name: '', title: '', company: '', quote: '', thumbnail: '', logo: '', industry: '', challenge: '', solution: '', results: '' },
  hero_trust_badges: { id: '', icon: '🔒', text: '' },
  homepage_industries_list: { id: '', title: '', description: '', link: '/', image: '' },
  analyst_reports: { id: '', tag: 'Report', title: '', stat1_value: '', stat1_label: '', stat2_value: '', stat2_label: '', link: '/products', image: '' },
  ai_success_cards: { id: '', tag: '', title: '', desc: '', link: '/contact', image: '' },
  demo_bullets: { id: '', text: '' },
  platform_arch_agents: { id: '', icon: '🤝', title: '', sub: '' },
  platform_arch_layers: { id: '', icon: '⚡', brand: '', tag: '', accent: 'var(--color-accent)', items: '' },
  platform_arch_customer360_items: { id: '', icon: '❤️', label: '' },
  platform_arch_data360_items: { id: '', icon: '🔴', label: '' },
  platform_arch_providers: { id: '', label: '' },
  nav_products: { id: '', title: '', desc: '', path: '/', iconName: 'Users', accent: 'bg-blue-50 text-blue-600 ring-blue-100' },
  nav_links: { id: '', label: '', labelKey: '', path: '/' },
  mission_bullets: { id: '', text: '' },
  pricing_tiers: { id: '', name: '', price: 'Quote', period: '', desc: '', features: '', cta: 'Request a Demo', tier_highlight: 'false' },
  pricing_faqs: { id: '', question: '', answer: '' },
  resources_cards: { id: '', title: '', description: '', path: '/', iconName: 'BookOpen', accent: 'bg-blue-50 text-blue-600 ring-blue-100', image: '' },
  blog_posts: { id: '', slug: '', title: '', excerpt: '', date: '', author: '', category: '', body: '', image: '' },
  guides_list: { id: '', title: '', desc: '', pages: '', type: 'PDF', image: '' },
  faq_items: { id: '', category: '', question: '', answer: '' },
  about_stats: { id: '', value: '', label: '', iconName: 'Building2' },
  company_sections: { id: '', title: '', description: '', path: '/', iconName: 'Building2', accent: 'bg-blue-50 text-blue-600 ring-blue-100', image: '' },
  company_stats: { id: '', value: '', label: '' },
  partners_programs: { id: '', title: '', desc: '', iconName: 'Users', accent: 'bg-blue-50 text-blue-600 ring-blue-100', image: '' },
  partners_benefits: { id: '', title: '', desc: '' },
  partners_list: { id: '', name: '', location: '', program: 'reseller', sectors: '', website: '' },
  careers_values: { id: '', title: '', desc: '', image: '' },
  open_roles: { id: '', title: '', dept: '', location: '', type: 'Full-time' },
  nav_solutions: { id: '', title: '', desc: '', path: '/', iconName: 'Factory', accent: 'bg-emerald-50 text-emerald-600 ring-emerald-100' },
  nav_resources: { id: '', title: '', desc: '', path: '/', iconName: 'BookOpen', accent: 'bg-blue-50 text-blue-600 ring-blue-100' },
  nav_company: { id: '', title: '', desc: '', path: '/', iconName: 'Building2', accent: 'bg-blue-50 text-blue-600 ring-blue-100' },
  footer_resources: { id: '', title: '', path: '/' },
  footer_company: { id: '', title: '', path: '/' },
};

export const ARRAY_ITEM_LABEL: Record<string, (item: Record<string, unknown>, index: number) => string> = {
  product_cards: (item, i) => String(item.title || item.titleKey || `Product ${i + 1}`),
  products_list: (item, i) => String(item.title || item.id || item.key || `Product ${i + 1}`),
  industries_list: (item, i) => String(item.title || item.id || `Industry ${i + 1}`),
  customer_stories: (item, i) => String(item.name || item.company || item.id || `Story ${i + 1}`),
  leadership_team: (item) => String(item.name || 'Team member'),
  events_list: (item) => String(item.title || 'Event'),
  events_highlights: (item, i) => String(item.text || `Highlight ${i + 1}`),
  stories_stats: (item, i) => String(item.label || item.value || `Stat ${i + 1}`),
  doc_categories: (item, i) => String(item.title || `Category ${i + 1}`),
  faqs: (item, i) => String(item.question || `FAQ ${i + 1}`),
  features: (item, i) => String(item.title || item.titleKey || `Feature ${i + 1}`),
  hero_trust_badges: (item, i) => String(item.text || `Badge ${i + 1}`),
  homepage_industries_list: (item, i) => String(item.title || `Industry ${i + 1}`),
  analyst_reports: (item, i) => String(item.title || `Report ${i + 1}`),
  ai_success_cards: (item, i) => String(item.title || `Card ${i + 1}`),
  values: (item, i) => String(item.title || item.titleKey || `Value ${i + 1}`),
  demo_bullets: (item, i) => String(item.text || `Bullet ${i + 1}`),
  platform_arch_agents: (item, i) => String(item.title || `Agent ${i + 1}`),
  platform_arch_layers: (item, i) => String(item.brand || `Layer ${i + 1}`),
  platform_arch_customer360_items: (item, i) => String(item.label || `Item ${i + 1}`),
  platform_arch_data360_items: (item, i) => String(item.label || `Item ${i + 1}`),
  platform_arch_providers: (item, i) => String(item.label || `Provider ${i + 1}`),
  nav_products: (item, i) => String(item.title || item.id || `Product ${i + 1}`),
  nav_links: (item, i) => String(item.label || item.labelKey || `Link ${i + 1}`),
  mission_bullets: (item, i) => String(item.text || `Bullet ${i + 1}`),
  pricing_tiers: (item, i) => String(item.name || item.id || `Tier ${i + 1}`),
  pricing_faqs: (item, i) => String(item.question || `FAQ ${i + 1}`),
  resources_cards: (item, i) => String(item.title || item.id || `Resource ${i + 1}`),
  blog_posts: (item, i) => String(item.title || item.slug || item.id || `Post ${i + 1}`),
  guides_list: (item, i) => String(item.title || item.id || `Guide ${i + 1}`),
  faq_items: (item, i) => String(item.question || `FAQ ${i + 1}`),
  about_stats: (item, i) => String(item.label || item.value || `Stat ${i + 1}`),
  company_sections: (item, i) => String(item.title || item.id || `Section ${i + 1}`),
  company_stats: (item, i) => String(item.label || item.value || `Stat ${i + 1}`),
  partners_programs: (item, i) => String(item.title || item.id || `Programme ${i + 1}`),
  partners_benefits: (item, i) => String(item.title || `Benefit ${i + 1}`),
  partners_list: (item, i) => String(item.name || item.id || `Partner ${i + 1}`),
  careers_values: (item, i) => String(item.title || `Value ${i + 1}`),
  open_roles: (item, i) => String(item.title || `Role ${i + 1}`),
  nav_solutions: (item, i) => String(item.title || item.id || `Sector ${i + 1}`),
  nav_resources: (item, i) => String(item.title || item.id || `Resource ${i + 1}`),
  nav_company: (item, i) => String(item.title || item.id || `Link ${i + 1}`),
  footer_resources: (item, i) => String(item.title || item.id || `Link ${i + 1}`),
  footer_company: (item, i) => String(item.title || item.id || `Link ${i + 1}`),
};

export function formatFieldLabel(key: string): string {
  return FIELD_META[key]?.label ?? key
    .replace(/_/g, ' ')
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

export function getFieldMeta(key: string): FieldMeta {
  return FIELD_META[key] ?? { label: formatFieldLabel(key), type: 'text' };
}
