import { translations } from '../i18n';

/** English defaults — matches what the site shows when CMS fields are empty. */
const en = translations.en;

export const CMS_DEFAULTS: Record<string, Record<string, string>> = {
  homepage: {
    hero_title: en.heroTitleLine1,
    hero_subtitle: en.heroTitleLine2,
    hero_desc: en.heroDescription,
    hero_cta: en.startFreeTrial,
    hero_cta_secondary: en.watchDemo,
    trusted_by_label: en.trustedBy,
    stats_modules: '11',
    stats_modules_label: 'ERP modules',
    stats_sectors: '12',
    stats_sectors_label: 'Industry sectors',
    stats_platform: '1',
    stats_platform_label: 'Unified platform',
    stats_integrations: '99.9%',
    stats_integrations_label: en.uptimeSLA,
    demo_title: 'Request a personalised demo',
    demo_desc: 'See how Marmidon ERP fits your organisation. Our team will tailor a demo to your modules and industry.',
    platform_intro_badge: en.platformIntroBadge,
    platform_intro_title: `${en.platformIntroTitle}`,
    platform_intro_desc: en.platformIntroDesc,
    product_section_title: `${en.completeSuiteTitle}`,
    product_section_desc: en.completeSuiteDesc,
    features_section_title: 'Why teams choose Marmidon',
    features_section_desc: 'Enterprise-grade capabilities out of the box — built for teams that need to move fast without compromising on security.',
    get_started_badge: en.getStartedBadge,
    get_started_title_1: en.getStartedTitle1,
    get_started_title_2: en.getStartedTitle2,
    get_started_title_3: en.getStartedTitle3,
    get_started_button: en.tryForFree,
    get_started_footnote: en.noCommitment,
    explore_all_products_label: en.exploreAllProducts,
    homepage_industries_link_label: en.learnMore,
    homepage_industries_cta: 'Explore all solutions',
    ai_success_card_link_label: en.learnMore,
  },
  products: {
    productsTitle: en.productsTitle,
    productsDesc: en.productsDesc,
    products_grid_title: 'Eleven modules. One ERP platform.',
    products_grid_desc: 'From finance and HR to inventory, manufacturing, and BI — every module connects on a single platform.',
    cta_title: 'Ready to get started?',
    cta_desc: 'Request a personalised demo and quote for the modules you need.',
    cta_button: en.startFreeTrialBtn,
    detail_cta_title: en.readyToGetStarted,
    detail_cta_desc: `${en.joinThousands} {{name}}.`,
    detail_cta_button: en.startFreeTrialBtn,
    detail_cta_secondary: 'View All Products',
    products_hero_cta_primary: en.startFreeTrialBtn,
    products_hero_cta_secondary: en.contactSales,
    spotlight_featured_label: 'Featured module',
    detail_hero_secondary_cta: en.viewAllProducts,
    detail_hero_primary_cta: en.startFreeTrialBtn,
    detail_outcomes_badge: 'Outcomes',
    detail_outcomes_title: en.benefitsTitle,
    detail_outcomes_desc: 'What your organisation gains when this module is live.',
    detail_integration_title: 'How it fits the Marmidon platform',
    detail_industries_title: 'Most relevant industries',
    detail_industries_desc: 'See how this module supports organisations in your sector.',
    detail_faq_title: 'Frequently asked questions',
    detail_related_title: 'Works best with',
    detail_related_desc: 'Modules that connect directly with this part of Marmidon ERP.',
  },
  industries: {
    industriesTitle: 'Solutions by industry',
    industriesDesc: 'Tailored Marmidon ERP for every sector.',
    industries_grid_title: 'Purpose-built for your sector',
    industries_grid_desc: 'Sector-fit module configurations for twelve industries.',
    cta_title: "Don't see your sector?",
    cta_desc: 'Marmidon adapts to any sector. Talk to our team for a custom solution.',
    cta_button: en.contactSales,
    detail_cta_title: 'Ready for {{name}}?',
    detail_cta_desc: 'Request a demo tailored to your sector and modules.',
    detail_cta_button: en.startFreeTrialBtn,
    detail_cta_secondary: 'View All Solutions',
    industries_hero_cta_primary: en.contactSales,
    industries_hero_cta_secondary: 'Explore Solutions',
    industries_list_cta_secondary: en.startFreeTrialBtn,
    detail_hero_primary_cta: en.startFreeTrialBtn,
    detail_hero_secondary_cta: en.contactSales,
    detail_helps_badge: 'How Marmidon helps',
    detail_helps_title: 'How Marmidon helps {{name}} organisations',
    detail_helps_desc: 'Practical outcomes when finance, operations, and industry workflows run on one ERP platform.',
    detail_pain_badge: 'Challenges',
    detail_pain_title: 'Common pain points',
    detail_pain_desc: 'We understand the unique challenges this industry faces.',
    detail_modules_badge: 'Modules',
    detail_modules_title: 'Recommended modules',
    detail_modules_desc: 'The Marmidon modules most relevant to this industry.',
    detail_stat_note: 'Typical results achieved by organisations in this sector after deploying Marmidon ERP.',
  },
  global: {
    footer_brand_name: 'Marmidon Global Solutions Limited',
    footer_tagline: 'Integrated ERP for finance, operations, and growth.',
    footer_website_url: 'https://www.marmidon.com',
    footer_copyright: '© 2026 Marmidon Global Solutions Limited. All rights reserved.',
    support_email: 'support@marmidon.com',
    support_phone: '0782-602854',
    footer_col_products: 'Products',
    footer_col_solutions: 'Solutions',
    footer_col_resources: 'Resources',
    footer_col_company: 'Company',
    footer_all_products_label: 'All products →',
    footer_all_solutions_label: 'All solutions →',
    footer_privacy_label: 'Privacy',
    footer_terms_label: 'Terms',
    footer_cookies_label: 'Cookies',
    footer_sitemap_label: 'Sitemap',
    faq_section_title: en.faqSectionTitle,
    page_eyebrow: 'Marmidon Global Solutions Limited',
    page_subtitle_suffix: 'by Marmidon',
    card_footer_label: en.learnMore,
  },
  pricing: {
    pricing_title: 'ERP pricing that scales with you',
    pricing_desc: 'Choose the modules and deployment model you need. Every plan starts with a personalised demo and quote.',
    pricing_hero_badge: 'Pricing',
    pricing_hero_cta: 'Request a Demo',
    pricing_enterprise_title: 'Need a custom solution?',
    pricing_enterprise_desc: 'Talk to our team about volume discounts, custom integrations, and dedicated support.',
    pricing_contact_cta: 'Contact Sales',
    pricing_faq_title: 'Frequently asked questions',
    pricing_faq_desc: 'Everything you need to know about our pricing and plans.',
    pricing_popular_label: 'Most Popular',
    cta_title: 'Ready to get started?',
    cta_desc: 'Request a personalised demo and quote for the modules you need.',
    cta_button: en.startFreeTrialBtn,
  },
  resources: {
    resources_title: 'Learn, explore, and grow',
    resources_desc: 'Access a wealth of knowledge to help you get the most out of the Marmidon platform.',
    resources_hero_badge: 'Resources',
    resources_card_link_label: 'Explore',
    cta_title: 'Ready to see Marmidon in action?',
    cta_desc: 'Book a personalised demo tailored to your modules and industry.',
    cta_button: en.startFreeTrialBtn,
  },
  blog: {
    blog_title: 'Marmidon blog',
    blog_desc: 'ERP insights, implementation guides, and stories from the team.',
    blog_hero_badge: 'Blog',
    blog_read_more_label: 'Read more',
    cta_title: 'Ready to see Marmidon in action?',
    cta_desc: 'Book a personalised demo tailored to your modules and industry.',
    cta_button: en.startFreeTrialBtn,
  },
  guides: {
    guides_title: 'Guides & whitepapers',
    guides_desc: 'In-depth resources to help you make informed decisions about your technology strategy.',
    guides_hero_badge: 'Guides',
    guides_download_label: 'Download',
    download_modal_desc: 'Enter your work email to receive this guide.',
    download_success_title: 'Download link sent',
    download_success_desc: 'Check your inbox for the guide. Our team will follow up with the PDF shortly.',
    download_button_label: 'Get the guide',
    cta_title: 'Ready to see Marmidon in action?',
    cta_desc: 'Book a personalised demo tailored to your modules and industry.',
    cta_button: en.startFreeTrialBtn,
  },
  faq_page: {
    faq_title: 'Frequently asked questions',
    faq_desc: 'Quick answers about Marmidon ERP modules, demos, pricing, and support.',
    faq_hero_badge: 'FAQs',
    faq_search_placeholder: 'Search FAQs…',
    cta_title: 'Ready to see Marmidon in action?',
    cta_desc: 'Book a personalised demo tailored to your modules and industry.',
    cta_button: en.startFreeTrialBtn,
  },
  company: {
    company_title: 'Marmidon Global Solutions',
    company_desc: 'We build technology that empowers businesses across Africa and the world to grow, automate, and transform.',
    company_hero_badge: 'Company',
    company_stats_title: 'Marmidon by the numbers',
    company_card_link_label: 'Learn more',
    cta_title: 'Ready to see Marmidon in action?',
    cta_desc: 'Book a personalised demo tailored to your modules and industry.',
    cta_button: en.startFreeTrialBtn,
  },
  partners: {
    partners_title: 'Grow with the Marmidon ecosystem',
    partners_desc: 'Join a global network of partners building, selling, and delivering Marmidon solutions.',
    partners_hero_badge: 'Partners',
    partners_cta: 'Become a partner',
    partners_programs_badge: 'Programmes',
    partners_programs_title: 'Partner programmes',
    partners_programs_desc: 'Find the programme that fits your business model and goals.',
    partners_benefits_badge: 'Benefits',
    partners_benefits_title: 'Why partner with Marmidon?',
    partners_benefits_desc: 'Access resources, training, and revenue opportunities.',
    cta_title: 'Ready to join the Marmidon partner ecosystem?',
    cta_desc: 'Apply today or speak with our partnerships team about programme fit.',
    cta_button: 'Apply to become a partner',
    cta_secondary_button: 'Talk to partnerships team',
  },
  partner_apply: {
    apply_hero_badge: 'Partner Application',
    apply_title: 'Become a Marmidon partner',
    apply_desc: 'Fill out the form below and our partnerships team will reach out within 5 business days.',
    form_first_name_label: 'First name *',
    form_last_name_label: 'Last name *',
    form_email_label: 'Work email *',
    form_company_label: 'Company name *',
    form_website_label: 'Company website',
    form_program_label: 'Partner programme *',
    form_message_label: 'Tell us about your business *',
    form_submit_label: 'Submit application',
    form_submitting_label: 'Submitting…',
    success_title: 'Application submitted',
    success_desc: 'Thank you for your interest in partnering with Marmidon. Our partnerships team will review your application and get back to you within 5 business days.',
    success_back_label: 'Back to home',
  },
  careers: {
    careers_title: 'Join the team building the future',
    careers_desc: 'At Marmidon, we are building enterprise software that empowers businesses across Africa and beyond. Come grow with us.',
    careers_hero_badge: 'Careers',
    careers_cta: 'View open roles',
    careers_values_badge: 'Why us?',
    careers_values_title: 'Life at Marmidon',
    careers_values_desc: 'We are building a culture where people do their best work.',
    careers_roles_badge: 'Openings',
    careers_roles_title: 'Open roles',
    careers_roles_desc: 'Find your next opportunity at Marmidon.',
    careers_apply_label: 'Apply',
    cta_title: 'Ready to see Marmidon in action?',
    cta_desc: 'Book a personalised demo tailored to your modules and industry.',
    cta_button: en.startFreeTrialBtn,
  },
  team: {
    team_hero_badge: 'Team',
    team_title: 'Our leadership team',
    team_desc: 'Meet the people driving innovation at Marmidon.',
    team_back_label: 'Back to Company',
    cta_title: 'Ready to see Marmidon in action?',
    cta_desc: 'Book a personalised demo tailored to your modules and industry.',
    cta_button: en.startFreeTrialBtn,
  },
  legal: {
    privacy_hero_badge: 'Privacy Statement',
    privacy_hero_title: 'Privacy Policy',
    privacy_hero_subtitle: 'Data protection & trust',
    privacy_hero_desc: 'Learn how we collect, safeguard, and use your information responsibly.',
    privacy_hero_cta: 'Contact Privacy Team',
    terms_hero_badge: 'Terms of Service',
    terms_hero_title: 'Terms of Service',
    terms_hero_subtitle: 'Legal terms & usage policies',
    terms_hero_desc: 'Review the rules that govern access to our platform, services, and website.',
    terms_hero_cta: 'Contact Legal',
    cookies_hero_badge: 'Cookie Policy',
    cookies_hero_title: 'Cookie Policy',
    cookies_hero_subtitle: 'How we use cookies',
    cookies_hero_desc: 'Understand how Marmidon uses cookies and similar technologies on our website.',
    cookies_hero_cta: 'Contact Us',
  },
  demo_request: {
    demo_hero_badge: 'Demo',
    demo_title: 'Request a personalised demo',
    demo_desc: 'See how Marmidon ERP fits your organisation. Our team will tailor a demo to your modules and industry.',
    form_first_name_label: 'First name *',
    form_last_name_label: 'Last name *',
    form_email_label: 'Work email *',
    form_company_label: 'Company name *',
    form_phone_label: 'Phone number',
    form_modules_label: 'Modules of interest *',
    form_industry_label: 'Industry',
    form_message_label: 'Tell us about your needs',
    form_submit_label: 'Request a Demo',
    form_submitting_label: 'Submitting…',
    success_title: 'Demo request received',
    success_desc: 'A member of our team will contact you within 24 hours to schedule your personalised demo.',
    success_back_label: 'Back to home',
  },
  contact: {
    contact_hero_badge: 'Support & Help',
    contactTitle: en.contactTitle,
    contactDesc: en.contactDesc,
    contact_hero_cta_primary: 'Send a Message',
    contact_hero_cta_secondary: 'Request a Demo',
    form_required_note: 'All fields marked * are required.',
    form_first_name_label: `${en.firstNameLabel} *`,
    form_last_name_label: `${en.lastNameLabel} *`,
    form_email_label: `${en.workEmailLabel} *`,
    form_phone_label: en.phoneInputLabel,
    form_company_label: `${en.companyLabel} *`,
    form_job_title_label: en.jobTitleLabel,
    form_interest_label: `${en.interestedInLabel} *`,
    form_message_label: `${en.messageLabel} *`,
    form_submit_label: 'Send Message',
    form_submitting_label: 'Sending…',
    success_title: 'Message Sent!',
    success_desc: 'Thank you for reaching out. Our team will get back to you within 24 hours.',
    success_again_label: 'Send Another Message',
  },
  events: {
    events_hero_badge: 'Events & Experiences',
    eventsTitle: 'Events & Experiences',
    eventsDesc: 'Participate in live summits, workshops, and partner forums designed to help your organisation grow with Marmidon.',
    events_hero_cta_primary: 'Request a Demo',
    events_hero_cta_secondary: 'Contact Us',
    events_section_badge: 'Upcoming Events',
    events_section_title: 'Learn, network, and lead change',
    events_section_desc: 'Experience Marmidon events tailored for customers, partners, and IT teams who want to modernize faster.',
    events_highlights_badge: 'Event Highlights',
    faq_section_badge: 'Event FAQs',
  },
};

export function getCmsDefault(section: string, key: string): string {
  return CMS_DEFAULTS[section]?.[key] ?? '';
}

/** Resolve stored CMS text, then configured default, then caller fallback. */
export function effectiveCmsText(
  stored: unknown,
  section: string,
  key: string,
  fallback = ''
): string {
  if (typeof stored === 'string' && stored.trim()) return stored.trim();
  const configured = getCmsDefault(section, key);
  if (configured) return configured;
  return fallback;
}
